<?php

declare(strict_types=1);

// AUTO-GENERATED by scripts/generate-namespaces.php — DO NOT EDIT.
// Run `composer generate:namespaces` to refresh from openapi.json.

namespace Astroway\Namespaces;

use Astroway\Astroway;

/** Service for agent.* endpoints. */
final class AgentService
{
    public function __construct(private readonly Astroway $client)
    {
    }

    /**
     * Agent tool definitions (GET /agent/tools).
     *
     * @param array{headers?: array<string, string>, query?: array<string, scalar|array<int|string, scalar>>} $options
     */
    public function toolsGet(array $options = []): mixed
    {
        $opts = [];
        if (!empty($options['query'])) {
            $opts['query'] = $options['query'];
        }
        if (!empty($options['headers'])) {
            $opts['headers'] = $options['headers'];
        }

        return $this->client->request('GET', '/agent/tools', $opts);
    }
}
