<?php

declare(strict_types=1);

// AUTO-GENERATED by scripts/generate-namespaces.php — DO NOT EDIT.
// Run `composer generate:namespaces` to refresh from openapi.json.

namespace Astroway\Namespaces;

use Astroway\Astroway;

/** Service for djamaspa.* endpoints. */
final class DjamaspaService
{
    public function __construct(private readonly Astroway $client)
    {
    }

    /**
     * Djamaspa (DEPRECATED — RED quality, slated for v2.0 sunset) (POST /djamaspa).
     *
     * @param array<string, mixed>|list<mixed>|object|null $body  Array, list, or DTO with `toArray()`.
     * @param array{headers?: array<string, string>, query?: array<string, scalar|array<int|string, scalar>>, idempotencyKey?: string} $options
     */
    public function compute(array|object|null $body = null, array $options = []): mixed
    {
        $opts = [];
        if ($body !== null) {
            $opts['json'] = $body;
        }
        if (!empty($options['query'])) {
            $opts['query'] = $options['query'];
        }
        if (!empty($options['headers'])) {
            $opts['headers'] = $options['headers'];
        }
        if (isset($options['idempotencyKey'])) {
            $opts['idempotencyKey'] = $options['idempotencyKey'];
        }

        return $this->client->request('POST', '/djamaspa', $opts);
    }
}
