<?php

declare(strict_types=1);

// AUTO-GENERATED by scripts/generate-namespaces.php — DO NOT EDIT.
// Run `composer generate:namespaces` to refresh from openapi.json.

namespace Astroway\Namespaces;

use Astroway\Astroway;

/** Service for esoteric.* endpoints. */
final class EsotericService
{
    public function __construct(private readonly Astroway $client)
    {
    }

    /**
     * Decode Angel Number (POST /esoteric/angel-numbers/decode).
     *
     * @param array<string, mixed>|list<mixed>|object|null $body  Array, list, or DTO with `toArray()`.
     * @param array{headers?: array<string, string>, query?: array<string, scalar|array<int|string, scalar>>, idempotencyKey?: string} $options
     */
    public function angelNumbersDecode(array|object|null $body = null, array $options = []): mixed
    {
        $opts = [];
        if ($body !== null) {
            $opts['json'] = $body;
        }
        if (!empty($options['query'])) {
            $opts['query'] = $options['query'];
        }
        if (!empty($options['headers'])) {
            $opts['headers'] = $options['headers'];
        }
        if (isset($options['idempotencyKey'])) {
            $opts['idempotencyKey'] = $options['idempotencyKey'];
        }

        return $this->client->request('POST', '/esoteric/angel-numbers/decode', $opts);
    }

    /**
     * Angel Numbers — Catalogue (GET /esoteric/angel-numbers).
     *
     * @param array{headers?: array<string, string>, query?: array<string, scalar|array<int|string, scalar>>} $options
     */
    public function angelNumbersGet(array $options = []): mixed
    {
        $opts = [];
        if (!empty($options['query'])) {
            $opts['query'] = $options['query'];
        }
        if (!empty($options['headers'])) {
            $opts['headers'] = $options['headers'];
        }

        return $this->client->request('GET', '/esoteric/angel-numbers', $opts);
    }

    /**
     * Daily Angel Number (GET /esoteric/angel-numbers/today).
     *
     * @param array{headers?: array<string, string>, query?: array<string, scalar|array<int|string, scalar>>} $options
     */
    public function angelNumbersTodayGet(array $options = []): mixed
    {
        $opts = [];
        if (!empty($options['query'])) {
            $opts['query'] = $options['query'];
        }
        if (!empty($options['headers'])) {
            $opts['headers'] = $options['headers'];
        }

        return $this->client->request('GET', '/esoteric/angel-numbers/today', $opts);
    }

    /**
     * Crystals — Full Directory (GET /esoteric/crystals).
     *
     * @param array{headers?: array<string, string>, query?: array<string, scalar|array<int|string, scalar>>} $options
     */
    public function crystalsGet(array $options = []): mixed
    {
        $opts = [];
        if (!empty($options['query'])) {
            $opts['query'] = $options['query'];
        }
        if (!empty($options['headers'])) {
            $opts['headers'] = $options['headers'];
        }

        return $this->client->request('GET', '/esoteric/crystals', $opts);
    }

    /**
     * Crystal Recommendations (POST /esoteric/crystals/recommend).
     *
     * @param array<string, mixed>|list<mixed>|object|null $body  Array, list, or DTO with `toArray()`.
     * @param array{headers?: array<string, string>, query?: array<string, scalar|array<int|string, scalar>>, idempotencyKey?: string} $options
     */
    public function crystalsRecommend(array|object|null $body = null, array $options = []): mixed
    {
        $opts = [];
        if ($body !== null) {
            $opts['json'] = $body;
        }
        if (!empty($options['query'])) {
            $opts['query'] = $options['query'];
        }
        if (!empty($options['headers'])) {
            $opts['headers'] = $options['headers'];
        }
        if (isset($options['idempotencyKey'])) {
            $opts['idempotencyKey'] = $options['idempotencyKey'];
        }

        return $this->client->request('POST', '/esoteric/crystals/recommend', $opts);
    }

    /**
     * Decode Dream Text (POST /esoteric/dreams/decode).
     *
     * @param array<string, mixed>|list<mixed>|object|null $body  Array, list, or DTO with `toArray()`.
     * @param array{headers?: array<string, string>, query?: array<string, scalar|array<int|string, scalar>>, idempotencyKey?: string} $options
     */
    public function dreamsDecode(array|object|null $body = null, array $options = []): mixed
    {
        $opts = [];
        if ($body !== null) {
            $opts['json'] = $body;
        }
        if (!empty($options['query'])) {
            $opts['query'] = $options['query'];
        }
        if (!empty($options['headers'])) {
            $opts['headers'] = $options['headers'];
        }
        if (isset($options['idempotencyKey'])) {
            $opts['idempotencyKey'] = $options['idempotencyKey'];
        }

        return $this->client->request('POST', '/esoteric/dreams/decode', $opts);
    }

    /**
     * Dream Symbol Dictionary (GET /esoteric/dreams).
     *
     * @param array{headers?: array<string, string>, query?: array<string, scalar|array<int|string, scalar>>} $options
     */
    public function dreamsGet(array $options = []): mixed
    {
        $opts = [];
        if (!empty($options['query'])) {
            $opts['query'] = $options['query'];
        }
        if (!empty($options['headers'])) {
            $opts['headers'] = $options['headers'];
        }

        return $this->client->request('GET', '/esoteric/dreams', $opts);
    }

    /**
     * Recurring Dream Themes (GET /esoteric/dreams/recurring-themes).
     *
     * @param array{headers?: array<string, string>, query?: array<string, scalar|array<int|string, scalar>>} $options
     */
    public function dreamsRecurringThemesGet(array $options = []): mixed
    {
        $opts = [];
        if (!empty($options['query'])) {
            $opts['query'] = $options['query'];
        }
        if (!empty($options['headers'])) {
            $opts['headers'] = $options['headers'];
        }

        return $this->client->request('GET', '/esoteric/dreams/recurring-themes', $opts);
    }
}
