<?php

declare(strict_types=1);

// AUTO-GENERATED by scripts/generate-namespaces.php — DO NOT EDIT.
// Run `composer generate:namespaces` to refresh from openapi.json.

namespace Astroway\Namespaces;

use Astroway\Astroway;

/** Service for mcp.* endpoints. */
final class McpService
{
    public function __construct(private readonly Astroway $client)
    {
    }

    /**
     * MCP Agent Debate (POST /mcp/agent-debate).
     *
     * @param array<string, mixed>|list<mixed>|object|null $body  Array, list, or DTO with `toArray()`.
     * @param array{headers?: array<string, string>, query?: array<string, scalar|array<int|string, scalar>>, idempotencyKey?: string} $options
     */
    public function agentDebate(array|object|null $body = null, array $options = []): mixed
    {
        $opts = [];
        if ($body !== null) {
            $opts['json'] = $body;
        }
        if (!empty($options['query'])) {
            $opts['query'] = $options['query'];
        }
        if (!empty($options['headers'])) {
            $opts['headers'] = $options['headers'];
        }
        if (isset($options['idempotencyKey'])) {
            $opts['idempotencyKey'] = $options['idempotencyKey'];
        }

        return $this->client->request('POST', '/mcp/agent-debate', $opts);
    }

    /**
     * MCP Multi-Agent Coordinate (POST /mcp/multi-agent-coordinate).
     *
     * @param array<string, mixed>|list<mixed>|object|null $body  Array, list, or DTO with `toArray()`.
     * @param array{headers?: array<string, string>, query?: array<string, scalar|array<int|string, scalar>>, idempotencyKey?: string} $options
     */
    public function multiAgentCoordinate(array|object|null $body = null, array $options = []): mixed
    {
        $opts = [];
        if ($body !== null) {
            $opts['json'] = $body;
        }
        if (!empty($options['query'])) {
            $opts['query'] = $options['query'];
        }
        if (!empty($options['headers'])) {
            $opts['headers'] = $options['headers'];
        }
        if (isset($options['idempotencyKey'])) {
            $opts['idempotencyKey'] = $options['idempotencyKey'];
        }

        return $this->client->request('POST', '/mcp/multi-agent-coordinate', $opts);
    }

    /**
     * MCP Multi-Chart Context (POST /mcp/multi-chart-context).
     *
     * @param array<string, mixed>|list<mixed>|object|null $body  Array, list, or DTO with `toArray()`.
     * @param array{headers?: array<string, string>, query?: array<string, scalar|array<int|string, scalar>>, idempotencyKey?: string} $options
     */
    public function multiChartContext(array|object|null $body = null, array $options = []): mixed
    {
        $opts = [];
        if ($body !== null) {
            $opts['json'] = $body;
        }
        if (!empty($options['query'])) {
            $opts['query'] = $options['query'];
        }
        if (!empty($options['headers'])) {
            $opts['headers'] = $options['headers'];
        }
        if (isset($options['idempotencyKey'])) {
            $opts['idempotencyKey'] = $options['idempotencyKey'];
        }

        return $this->client->request('POST', '/mcp/multi-chart-context', $opts);
    }

    /**
     * MCP RAG Search (POST /mcp/rag-search).
     *
     * @param array<string, mixed>|list<mixed>|object|null $body  Array, list, or DTO with `toArray()`.
     * @param array{headers?: array<string, string>, query?: array<string, scalar|array<int|string, scalar>>, idempotencyKey?: string} $options
     */
    public function ragSearch(array|object|null $body = null, array $options = []): mixed
    {
        $opts = [];
        if ($body !== null) {
            $opts['json'] = $body;
        }
        if (!empty($options['query'])) {
            $opts['query'] = $options['query'];
        }
        if (!empty($options['headers'])) {
            $opts['headers'] = $options['headers'];
        }
        if (isset($options['idempotencyKey'])) {
            $opts['idempotencyKey'] = $options['idempotencyKey'];
        }

        return $this->client->request('POST', '/mcp/rag-search', $opts);
    }

    /**
     * MCP Streaming Chat (POST /mcp/streaming).
     *
     * @param array<string, mixed>|list<mixed>|object|null $body  Array, list, or DTO with `toArray()`.
     * @param array{headers?: array<string, string>, query?: array<string, scalar|array<int|string, scalar>>, idempotencyKey?: string} $options
     */
    public function streaming(array|object|null $body = null, array $options = []): mixed
    {
        $opts = [];
        if ($body !== null) {
            $opts['json'] = $body;
        }
        if (!empty($options['query'])) {
            $opts['query'] = $options['query'];
        }
        if (!empty($options['headers'])) {
            $opts['headers'] = $options['headers'];
        }
        if (isset($options['idempotencyKey'])) {
            $opts['idempotencyKey'] = $options['idempotencyKey'];
        }

        return $this->client->request('POST', '/mcp/streaming', $opts);
    }

    /**
     * MCP Tool-Call Stream (POST /mcp/tool-call-stream).
     *
     * @param array<string, mixed>|list<mixed>|object|null $body  Array, list, or DTO with `toArray()`.
     * @param array{headers?: array<string, string>, query?: array<string, scalar|array<int|string, scalar>>, idempotencyKey?: string} $options
     */
    public function toolCallStream(array|object|null $body = null, array $options = []): mixed
    {
        $opts = [];
        if ($body !== null) {
            $opts['json'] = $body;
        }
        if (!empty($options['query'])) {
            $opts['query'] = $options['query'];
        }
        if (!empty($options['headers'])) {
            $opts['headers'] = $options['headers'];
        }
        if (isset($options['idempotencyKey'])) {
            $opts['idempotencyKey'] = $options['idempotencyKey'];
        }

        return $this->client->request('POST', '/mcp/tool-call-stream', $opts);
    }
}
