<?php

declare(strict_types=1);

// AUTO-GENERATED by scripts/generate-namespaces.php — DO NOT EDIT.
// Run `composer generate:namespaces` to refresh from openapi.json.

namespace Astroway\Namespaces;

use Astroway\Astroway;

/** Service for numerology.* endpoints. */
final class NumerologyService
{
    public function __construct(private readonly Astroway $client)
    {
    }

    /**
     * Balance (chaldean) (POST /numerology/chaldean/balance).
     *
     * @param array<string, mixed>|list<mixed>|object|null $body  Array, list, or DTO with `toArray()`.
     * @param array{headers?: array<string, string>, query?: array<string, scalar|array<int|string, scalar>>, idempotencyKey?: string} $options
     */
    public function chaldeanBalance(array|object|null $body = null, array $options = []): mixed
    {
        $opts = [];
        if ($body !== null) {
            $opts['json'] = $body;
        }
        if (!empty($options['query'])) {
            $opts['query'] = $options['query'];
        }
        if (!empty($options['headers'])) {
            $opts['headers'] = $options['headers'];
        }
        if (isset($options['idempotencyKey'])) {
            $opts['idempotencyKey'] = $options['idempotencyKey'];
        }

        return $this->client->request('POST', '/numerology/chaldean/balance', $opts);
    }

    /**
     * Birthday (chaldean) (POST /numerology/chaldean/birthday).
     *
     * @param array<string, mixed>|list<mixed>|object|null $body  Array, list, or DTO with `toArray()`.
     * @param array{headers?: array<string, string>, query?: array<string, scalar|array<int|string, scalar>>, idempotencyKey?: string} $options
     */
    public function chaldeanBirthday(array|object|null $body = null, array $options = []): mixed
    {
        $opts = [];
        if ($body !== null) {
            $opts['json'] = $body;
        }
        if (!empty($options['query'])) {
            $opts['query'] = $options['query'];
        }
        if (!empty($options['headers'])) {
            $opts['headers'] = $options['headers'];
        }
        if (isset($options['idempotencyKey'])) {
            $opts['idempotencyKey'] = $options['idempotencyKey'];
        }

        return $this->client->request('POST', '/numerology/chaldean/birthday', $opts);
    }

    /**
     * Challenge Cycles (chaldean) (POST /numerology/chaldean/challenge).
     *
     * @param array<string, mixed>|list<mixed>|object|null $body  Array, list, or DTO with `toArray()`.
     * @param array{headers?: array<string, string>, query?: array<string, scalar|array<int|string, scalar>>, idempotencyKey?: string} $options
     */
    public function chaldeanChallenge(array|object|null $body = null, array $options = []): mixed
    {
        $opts = [];
        if ($body !== null) {
            $opts['json'] = $body;
        }
        if (!empty($options['query'])) {
            $opts['query'] = $options['query'];
        }
        if (!empty($options['headers'])) {
            $opts['headers'] = $options['headers'];
        }
        if (isset($options['idempotencyKey'])) {
            $opts['idempotencyKey'] = $options['idempotencyKey'];
        }

        return $this->client->request('POST', '/numerology/chaldean/challenge', $opts);
    }

    /**
     * Expression / Destiny (chaldean) (POST /numerology/chaldean/expression).
     *
     * @param array<string, mixed>|list<mixed>|object|null $body  Array, list, or DTO with `toArray()`.
     * @param array{headers?: array<string, string>, query?: array<string, scalar|array<int|string, scalar>>, idempotencyKey?: string} $options
     */
    public function chaldeanExpression(array|object|null $body = null, array $options = []): mixed
    {
        $opts = [];
        if ($body !== null) {
            $opts['json'] = $body;
        }
        if (!empty($options['query'])) {
            $opts['query'] = $options['query'];
        }
        if (!empty($options['headers'])) {
            $opts['headers'] = $options['headers'];
        }
        if (isset($options['idempotencyKey'])) {
            $opts['idempotencyKey'] = $options['idempotencyKey'];
        }

        return $this->client->request('POST', '/numerology/chaldean/expression', $opts);
    }

    /**
     * Life Path Number (chaldean) (POST /numerology/chaldean/life-path).
     *
     * @param array<string, mixed>|list<mixed>|object|null $body  Array, list, or DTO with `toArray()`.
     * @param array{headers?: array<string, string>, query?: array<string, scalar|array<int|string, scalar>>, idempotencyKey?: string} $options
     */
    public function chaldeanLifePath(array|object|null $body = null, array $options = []): mixed
    {
        $opts = [];
        if ($body !== null) {
            $opts['json'] = $body;
        }
        if (!empty($options['query'])) {
            $opts['query'] = $options['query'];
        }
        if (!empty($options['headers'])) {
            $opts['headers'] = $options['headers'];
        }
        if (isset($options['idempotencyKey'])) {
            $opts['idempotencyKey'] = $options['idempotencyKey'];
        }

        return $this->client->request('POST', '/numerology/chaldean/life-path', $opts);
    }

    /**
     * Maturity (chaldean) (POST /numerology/chaldean/maturity).
     *
     * @param array<string, mixed>|list<mixed>|object|null $body  Array, list, or DTO with `toArray()`.
     * @param array{headers?: array<string, string>, query?: array<string, scalar|array<int|string, scalar>>, idempotencyKey?: string} $options
     */
    public function chaldeanMaturity(array|object|null $body = null, array $options = []): mixed
    {
        $opts = [];
        if ($body !== null) {
            $opts['json'] = $body;
        }
        if (!empty($options['query'])) {
            $opts['query'] = $options['query'];
        }
        if (!empty($options['headers'])) {
            $opts['headers'] = $options['headers'];
        }
        if (isset($options['idempotencyKey'])) {
            $opts['idempotencyKey'] = $options['idempotencyKey'];
        }

        return $this->client->request('POST', '/numerology/chaldean/maturity', $opts);
    }

    /**
     * Personal Year (chaldean) (POST /numerology/chaldean/personal-year).
     *
     * @param array<string, mixed>|list<mixed>|object|null $body  Array, list, or DTO with `toArray()`.
     * @param array{headers?: array<string, string>, query?: array<string, scalar|array<int|string, scalar>>, idempotencyKey?: string} $options
     */
    public function chaldeanPersonalYear(array|object|null $body = null, array $options = []): mixed
    {
        $opts = [];
        if ($body !== null) {
            $opts['json'] = $body;
        }
        if (!empty($options['query'])) {
            $opts['query'] = $options['query'];
        }
        if (!empty($options['headers'])) {
            $opts['headers'] = $options['headers'];
        }
        if (isset($options['idempotencyKey'])) {
            $opts['idempotencyKey'] = $options['idempotencyKey'];
        }

        return $this->client->request('POST', '/numerology/chaldean/personal-year', $opts);
    }

    /**
     * Personality (chaldean) (POST /numerology/chaldean/personality).
     *
     * @param array<string, mixed>|list<mixed>|object|null $body  Array, list, or DTO with `toArray()`.
     * @param array{headers?: array<string, string>, query?: array<string, scalar|array<int|string, scalar>>, idempotencyKey?: string} $options
     */
    public function chaldeanPersonality(array|object|null $body = null, array $options = []): mixed
    {
        $opts = [];
        if ($body !== null) {
            $opts['json'] = $body;
        }
        if (!empty($options['query'])) {
            $opts['query'] = $options['query'];
        }
        if (!empty($options['headers'])) {
            $opts['headers'] = $options['headers'];
        }
        if (isset($options['idempotencyKey'])) {
            $opts['idempotencyKey'] = $options['idempotencyKey'];
        }

        return $this->client->request('POST', '/numerology/chaldean/personality', $opts);
    }

    /**
     * Pinnacle Cycles (chaldean) (POST /numerology/chaldean/pinnacles).
     *
     * @param array<string, mixed>|list<mixed>|object|null $body  Array, list, or DTO with `toArray()`.
     * @param array{headers?: array<string, string>, query?: array<string, scalar|array<int|string, scalar>>, idempotencyKey?: string} $options
     */
    public function chaldeanPinnacles(array|object|null $body = null, array $options = []): mixed
    {
        $opts = [];
        if ($body !== null) {
            $opts['json'] = $body;
        }
        if (!empty($options['query'])) {
            $opts['query'] = $options['query'];
        }
        if (!empty($options['headers'])) {
            $opts['headers'] = $options['headers'];
        }
        if (isset($options['idempotencyKey'])) {
            $opts['idempotencyKey'] = $options['idempotencyKey'];
        }

        return $this->client->request('POST', '/numerology/chaldean/pinnacles', $opts);
    }

    /**
     * Soul Urge / Heart's Desire (chaldean) (POST /numerology/chaldean/soul-urge).
     *
     * @param array<string, mixed>|list<mixed>|object|null $body  Array, list, or DTO with `toArray()`.
     * @param array{headers?: array<string, string>, query?: array<string, scalar|array<int|string, scalar>>, idempotencyKey?: string} $options
     */
    public function chaldeanSoulUrge(array|object|null $body = null, array $options = []): mixed
    {
        $opts = [];
        if ($body !== null) {
            $opts['json'] = $body;
        }
        if (!empty($options['query'])) {
            $opts['query'] = $options['query'];
        }
        if (!empty($options['headers'])) {
            $opts['headers'] = $options['headers'];
        }
        if (isset($options['idempotencyKey'])) {
            $opts['idempotencyKey'] = $options['idempotencyKey'];
        }

        return $this->client->request('POST', '/numerology/chaldean/soul-urge', $opts);
    }

    /**
     * Balance (kabbalistic) (POST /numerology/kabbalistic/balance).
     *
     * @param array<string, mixed>|list<mixed>|object|null $body  Array, list, or DTO with `toArray()`.
     * @param array{headers?: array<string, string>, query?: array<string, scalar|array<int|string, scalar>>, idempotencyKey?: string} $options
     */
    public function kabbalisticBalance(array|object|null $body = null, array $options = []): mixed
    {
        $opts = [];
        if ($body !== null) {
            $opts['json'] = $body;
        }
        if (!empty($options['query'])) {
            $opts['query'] = $options['query'];
        }
        if (!empty($options['headers'])) {
            $opts['headers'] = $options['headers'];
        }
        if (isset($options['idempotencyKey'])) {
            $opts['idempotencyKey'] = $options['idempotencyKey'];
        }

        return $this->client->request('POST', '/numerology/kabbalistic/balance', $opts);
    }

    /**
     * Birthday (kabbalistic) (POST /numerology/kabbalistic/birthday).
     *
     * @param array<string, mixed>|list<mixed>|object|null $body  Array, list, or DTO with `toArray()`.
     * @param array{headers?: array<string, string>, query?: array<string, scalar|array<int|string, scalar>>, idempotencyKey?: string} $options
     */
    public function kabbalisticBirthday(array|object|null $body = null, array $options = []): mixed
    {
        $opts = [];
        if ($body !== null) {
            $opts['json'] = $body;
        }
        if (!empty($options['query'])) {
            $opts['query'] = $options['query'];
        }
        if (!empty($options['headers'])) {
            $opts['headers'] = $options['headers'];
        }
        if (isset($options['idempotencyKey'])) {
            $opts['idempotencyKey'] = $options['idempotencyKey'];
        }

        return $this->client->request('POST', '/numerology/kabbalistic/birthday', $opts);
    }

    /**
     * Challenge Cycles (kabbalistic) (POST /numerology/kabbalistic/challenge).
     *
     * @param array<string, mixed>|list<mixed>|object|null $body  Array, list, or DTO with `toArray()`.
     * @param array{headers?: array<string, string>, query?: array<string, scalar|array<int|string, scalar>>, idempotencyKey?: string} $options
     */
    public function kabbalisticChallenge(array|object|null $body = null, array $options = []): mixed
    {
        $opts = [];
        if ($body !== null) {
            $opts['json'] = $body;
        }
        if (!empty($options['query'])) {
            $opts['query'] = $options['query'];
        }
        if (!empty($options['headers'])) {
            $opts['headers'] = $options['headers'];
        }
        if (isset($options['idempotencyKey'])) {
            $opts['idempotencyKey'] = $options['idempotencyKey'];
        }

        return $this->client->request('POST', '/numerology/kabbalistic/challenge', $opts);
    }

    /**
     * Expression / Destiny (kabbalistic) (POST /numerology/kabbalistic/expression).
     *
     * @param array<string, mixed>|list<mixed>|object|null $body  Array, list, or DTO with `toArray()`.
     * @param array{headers?: array<string, string>, query?: array<string, scalar|array<int|string, scalar>>, idempotencyKey?: string} $options
     */
    public function kabbalisticExpression(array|object|null $body = null, array $options = []): mixed
    {
        $opts = [];
        if ($body !== null) {
            $opts['json'] = $body;
        }
        if (!empty($options['query'])) {
            $opts['query'] = $options['query'];
        }
        if (!empty($options['headers'])) {
            $opts['headers'] = $options['headers'];
        }
        if (isset($options['idempotencyKey'])) {
            $opts['idempotencyKey'] = $options['idempotencyKey'];
        }

        return $this->client->request('POST', '/numerology/kabbalistic/expression', $opts);
    }

    /**
     * Life Path Number (kabbalistic) (POST /numerology/kabbalistic/life-path).
     *
     * @param array<string, mixed>|list<mixed>|object|null $body  Array, list, or DTO with `toArray()`.
     * @param array{headers?: array<string, string>, query?: array<string, scalar|array<int|string, scalar>>, idempotencyKey?: string} $options
     */
    public function kabbalisticLifePath(array|object|null $body = null, array $options = []): mixed
    {
        $opts = [];
        if ($body !== null) {
            $opts['json'] = $body;
        }
        if (!empty($options['query'])) {
            $opts['query'] = $options['query'];
        }
        if (!empty($options['headers'])) {
            $opts['headers'] = $options['headers'];
        }
        if (isset($options['idempotencyKey'])) {
            $opts['idempotencyKey'] = $options['idempotencyKey'];
        }

        return $this->client->request('POST', '/numerology/kabbalistic/life-path', $opts);
    }

    /**
     * Maturity (kabbalistic) (POST /numerology/kabbalistic/maturity).
     *
     * @param array<string, mixed>|list<mixed>|object|null $body  Array, list, or DTO with `toArray()`.
     * @param array{headers?: array<string, string>, query?: array<string, scalar|array<int|string, scalar>>, idempotencyKey?: string} $options
     */
    public function kabbalisticMaturity(array|object|null $body = null, array $options = []): mixed
    {
        $opts = [];
        if ($body !== null) {
            $opts['json'] = $body;
        }
        if (!empty($options['query'])) {
            $opts['query'] = $options['query'];
        }
        if (!empty($options['headers'])) {
            $opts['headers'] = $options['headers'];
        }
        if (isset($options['idempotencyKey'])) {
            $opts['idempotencyKey'] = $options['idempotencyKey'];
        }

        return $this->client->request('POST', '/numerology/kabbalistic/maturity', $opts);
    }

    /**
     * Personal Year (kabbalistic) (POST /numerology/kabbalistic/personal-year).
     *
     * @param array<string, mixed>|list<mixed>|object|null $body  Array, list, or DTO with `toArray()`.
     * @param array{headers?: array<string, string>, query?: array<string, scalar|array<int|string, scalar>>, idempotencyKey?: string} $options
     */
    public function kabbalisticPersonalYear(array|object|null $body = null, array $options = []): mixed
    {
        $opts = [];
        if ($body !== null) {
            $opts['json'] = $body;
        }
        if (!empty($options['query'])) {
            $opts['query'] = $options['query'];
        }
        if (!empty($options['headers'])) {
            $opts['headers'] = $options['headers'];
        }
        if (isset($options['idempotencyKey'])) {
            $opts['idempotencyKey'] = $options['idempotencyKey'];
        }

        return $this->client->request('POST', '/numerology/kabbalistic/personal-year', $opts);
    }

    /**
     * Personality (kabbalistic) (POST /numerology/kabbalistic/personality).
     *
     * @param array<string, mixed>|list<mixed>|object|null $body  Array, list, or DTO with `toArray()`.
     * @param array{headers?: array<string, string>, query?: array<string, scalar|array<int|string, scalar>>, idempotencyKey?: string} $options
     */
    public function kabbalisticPersonality(array|object|null $body = null, array $options = []): mixed
    {
        $opts = [];
        if ($body !== null) {
            $opts['json'] = $body;
        }
        if (!empty($options['query'])) {
            $opts['query'] = $options['query'];
        }
        if (!empty($options['headers'])) {
            $opts['headers'] = $options['headers'];
        }
        if (isset($options['idempotencyKey'])) {
            $opts['idempotencyKey'] = $options['idempotencyKey'];
        }

        return $this->client->request('POST', '/numerology/kabbalistic/personality', $opts);
    }

    /**
     * Pinnacle Cycles (kabbalistic) (POST /numerology/kabbalistic/pinnacles).
     *
     * @param array<string, mixed>|list<mixed>|object|null $body  Array, list, or DTO with `toArray()`.
     * @param array{headers?: array<string, string>, query?: array<string, scalar|array<int|string, scalar>>, idempotencyKey?: string} $options
     */
    public function kabbalisticPinnacles(array|object|null $body = null, array $options = []): mixed
    {
        $opts = [];
        if ($body !== null) {
            $opts['json'] = $body;
        }
        if (!empty($options['query'])) {
            $opts['query'] = $options['query'];
        }
        if (!empty($options['headers'])) {
            $opts['headers'] = $options['headers'];
        }
        if (isset($options['idempotencyKey'])) {
            $opts['idempotencyKey'] = $options['idempotencyKey'];
        }

        return $this->client->request('POST', '/numerology/kabbalistic/pinnacles', $opts);
    }

    /**
     * Soul Urge / Heart's Desire (kabbalistic) (POST /numerology/kabbalistic/soul-urge).
     *
     * @param array<string, mixed>|list<mixed>|object|null $body  Array, list, or DTO with `toArray()`.
     * @param array{headers?: array<string, string>, query?: array<string, scalar|array<int|string, scalar>>, idempotencyKey?: string} $options
     */
    public function kabbalisticSoulUrge(array|object|null $body = null, array $options = []): mixed
    {
        $opts = [];
        if ($body !== null) {
            $opts['json'] = $body;
        }
        if (!empty($options['query'])) {
            $opts['query'] = $options['query'];
        }
        if (!empty($options['headers'])) {
            $opts['headers'] = $options['headers'];
        }
        if (isset($options['idempotencyKey'])) {
            $opts['idempotencyKey'] = $options['idempotencyKey'];
        }

        return $this->client->request('POST', '/numerology/kabbalistic/soul-urge', $opts);
    }

    /**
     * Balance (kabbalistic-strict) (POST /numerology/kabbalistic-strict/balance).
     *
     * @param array<string, mixed>|list<mixed>|object|null $body  Array, list, or DTO with `toArray()`.
     * @param array{headers?: array<string, string>, query?: array<string, scalar|array<int|string, scalar>>, idempotencyKey?: string} $options
     */
    public function kabbalisticStrictBalance(array|object|null $body = null, array $options = []): mixed
    {
        $opts = [];
        if ($body !== null) {
            $opts['json'] = $body;
        }
        if (!empty($options['query'])) {
            $opts['query'] = $options['query'];
        }
        if (!empty($options['headers'])) {
            $opts['headers'] = $options['headers'];
        }
        if (isset($options['idempotencyKey'])) {
            $opts['idempotencyKey'] = $options['idempotencyKey'];
        }

        return $this->client->request('POST', '/numerology/kabbalistic-strict/balance', $opts);
    }

    /**
     * Birthday (kabbalistic-strict) (POST /numerology/kabbalistic-strict/birthday).
     *
     * @param array<string, mixed>|list<mixed>|object|null $body  Array, list, or DTO with `toArray()`.
     * @param array{headers?: array<string, string>, query?: array<string, scalar|array<int|string, scalar>>, idempotencyKey?: string} $options
     */
    public function kabbalisticStrictBirthday(array|object|null $body = null, array $options = []): mixed
    {
        $opts = [];
        if ($body !== null) {
            $opts['json'] = $body;
        }
        if (!empty($options['query'])) {
            $opts['query'] = $options['query'];
        }
        if (!empty($options['headers'])) {
            $opts['headers'] = $options['headers'];
        }
        if (isset($options['idempotencyKey'])) {
            $opts['idempotencyKey'] = $options['idempotencyKey'];
        }

        return $this->client->request('POST', '/numerology/kabbalistic-strict/birthday', $opts);
    }

    /**
     * Challenge Cycles (kabbalistic-strict) (POST /numerology/kabbalistic-strict/challenge).
     *
     * @param array<string, mixed>|list<mixed>|object|null $body  Array, list, or DTO with `toArray()`.
     * @param array{headers?: array<string, string>, query?: array<string, scalar|array<int|string, scalar>>, idempotencyKey?: string} $options
     */
    public function kabbalisticStrictChallenge(array|object|null $body = null, array $options = []): mixed
    {
        $opts = [];
        if ($body !== null) {
            $opts['json'] = $body;
        }
        if (!empty($options['query'])) {
            $opts['query'] = $options['query'];
        }
        if (!empty($options['headers'])) {
            $opts['headers'] = $options['headers'];
        }
        if (isset($options['idempotencyKey'])) {
            $opts['idempotencyKey'] = $options['idempotencyKey'];
        }

        return $this->client->request('POST', '/numerology/kabbalistic-strict/challenge', $opts);
    }

    /**
     * Expression / Destiny (kabbalistic-strict) (POST /numerology/kabbalistic-strict/expression).
     *
     * @param array<string, mixed>|list<mixed>|object|null $body  Array, list, or DTO with `toArray()`.
     * @param array{headers?: array<string, string>, query?: array<string, scalar|array<int|string, scalar>>, idempotencyKey?: string} $options
     */
    public function kabbalisticStrictExpression(array|object|null $body = null, array $options = []): mixed
    {
        $opts = [];
        if ($body !== null) {
            $opts['json'] = $body;
        }
        if (!empty($options['query'])) {
            $opts['query'] = $options['query'];
        }
        if (!empty($options['headers'])) {
            $opts['headers'] = $options['headers'];
        }
        if (isset($options['idempotencyKey'])) {
            $opts['idempotencyKey'] = $options['idempotencyKey'];
        }

        return $this->client->request('POST', '/numerology/kabbalistic-strict/expression', $opts);
    }

    /**
     * Life Path Number (kabbalistic-strict) (POST /numerology/kabbalistic-strict/life-path).
     *
     * @param array<string, mixed>|list<mixed>|object|null $body  Array, list, or DTO with `toArray()`.
     * @param array{headers?: array<string, string>, query?: array<string, scalar|array<int|string, scalar>>, idempotencyKey?: string} $options
     */
    public function kabbalisticStrictLifePath(array|object|null $body = null, array $options = []): mixed
    {
        $opts = [];
        if ($body !== null) {
            $opts['json'] = $body;
        }
        if (!empty($options['query'])) {
            $opts['query'] = $options['query'];
        }
        if (!empty($options['headers'])) {
            $opts['headers'] = $options['headers'];
        }
        if (isset($options['idempotencyKey'])) {
            $opts['idempotencyKey'] = $options['idempotencyKey'];
        }

        return $this->client->request('POST', '/numerology/kabbalistic-strict/life-path', $opts);
    }

    /**
     * Maturity (kabbalistic-strict) (POST /numerology/kabbalistic-strict/maturity).
     *
     * @param array<string, mixed>|list<mixed>|object|null $body  Array, list, or DTO with `toArray()`.
     * @param array{headers?: array<string, string>, query?: array<string, scalar|array<int|string, scalar>>, idempotencyKey?: string} $options
     */
    public function kabbalisticStrictMaturity(array|object|null $body = null, array $options = []): mixed
    {
        $opts = [];
        if ($body !== null) {
            $opts['json'] = $body;
        }
        if (!empty($options['query'])) {
            $opts['query'] = $options['query'];
        }
        if (!empty($options['headers'])) {
            $opts['headers'] = $options['headers'];
        }
        if (isset($options['idempotencyKey'])) {
            $opts['idempotencyKey'] = $options['idempotencyKey'];
        }

        return $this->client->request('POST', '/numerology/kabbalistic-strict/maturity', $opts);
    }

    /**
     * Personal Year (kabbalistic-strict) (POST /numerology/kabbalistic-strict/personal-year).
     *
     * @param array<string, mixed>|list<mixed>|object|null $body  Array, list, or DTO with `toArray()`.
     * @param array{headers?: array<string, string>, query?: array<string, scalar|array<int|string, scalar>>, idempotencyKey?: string} $options
     */
    public function kabbalisticStrictPersonalYear(array|object|null $body = null, array $options = []): mixed
    {
        $opts = [];
        if ($body !== null) {
            $opts['json'] = $body;
        }
        if (!empty($options['query'])) {
            $opts['query'] = $options['query'];
        }
        if (!empty($options['headers'])) {
            $opts['headers'] = $options['headers'];
        }
        if (isset($options['idempotencyKey'])) {
            $opts['idempotencyKey'] = $options['idempotencyKey'];
        }

        return $this->client->request('POST', '/numerology/kabbalistic-strict/personal-year', $opts);
    }

    /**
     * Personality (kabbalistic-strict) (POST /numerology/kabbalistic-strict/personality).
     *
     * @param array<string, mixed>|list<mixed>|object|null $body  Array, list, or DTO with `toArray()`.
     * @param array{headers?: array<string, string>, query?: array<string, scalar|array<int|string, scalar>>, idempotencyKey?: string} $options
     */
    public function kabbalisticStrictPersonality(array|object|null $body = null, array $options = []): mixed
    {
        $opts = [];
        if ($body !== null) {
            $opts['json'] = $body;
        }
        if (!empty($options['query'])) {
            $opts['query'] = $options['query'];
        }
        if (!empty($options['headers'])) {
            $opts['headers'] = $options['headers'];
        }
        if (isset($options['idempotencyKey'])) {
            $opts['idempotencyKey'] = $options['idempotencyKey'];
        }

        return $this->client->request('POST', '/numerology/kabbalistic-strict/personality', $opts);
    }

    /**
     * Pinnacle Cycles (kabbalistic-strict) (POST /numerology/kabbalistic-strict/pinnacles).
     *
     * @param array<string, mixed>|list<mixed>|object|null $body  Array, list, or DTO with `toArray()`.
     * @param array{headers?: array<string, string>, query?: array<string, scalar|array<int|string, scalar>>, idempotencyKey?: string} $options
     */
    public function kabbalisticStrictPinnacles(array|object|null $body = null, array $options = []): mixed
    {
        $opts = [];
        if ($body !== null) {
            $opts['json'] = $body;
        }
        if (!empty($options['query'])) {
            $opts['query'] = $options['query'];
        }
        if (!empty($options['headers'])) {
            $opts['headers'] = $options['headers'];
        }
        if (isset($options['idempotencyKey'])) {
            $opts['idempotencyKey'] = $options['idempotencyKey'];
        }

        return $this->client->request('POST', '/numerology/kabbalistic-strict/pinnacles', $opts);
    }

    /**
     * Soul Urge / Heart's Desire (kabbalistic-strict) (POST /numerology/kabbalistic-strict/soul-urge).
     *
     * @param array<string, mixed>|list<mixed>|object|null $body  Array, list, or DTO with `toArray()`.
     * @param array{headers?: array<string, string>, query?: array<string, scalar|array<int|string, scalar>>, idempotencyKey?: string} $options
     */
    public function kabbalisticStrictSoulUrge(array|object|null $body = null, array $options = []): mixed
    {
        $opts = [];
        if ($body !== null) {
            $opts['json'] = $body;
        }
        if (!empty($options['query'])) {
            $opts['query'] = $options['query'];
        }
        if (!empty($options['headers'])) {
            $opts['headers'] = $options['headers'];
        }
        if (isset($options['idempotencyKey'])) {
            $opts['idempotencyKey'] = $options['idempotencyKey'];
        }

        return $this->client->request('POST', '/numerology/kabbalistic-strict/soul-urge', $opts);
    }

    /**
     * Balance (pythagorean) (POST /numerology/pythagorean/balance).
     *
     * @param array<string, mixed>|list<mixed>|object|null $body  Array, list, or DTO with `toArray()`.
     * @param array{headers?: array<string, string>, query?: array<string, scalar|array<int|string, scalar>>, idempotencyKey?: string} $options
     */
    public function pythagoreanBalance(array|object|null $body = null, array $options = []): mixed
    {
        $opts = [];
        if ($body !== null) {
            $opts['json'] = $body;
        }
        if (!empty($options['query'])) {
            $opts['query'] = $options['query'];
        }
        if (!empty($options['headers'])) {
            $opts['headers'] = $options['headers'];
        }
        if (isset($options['idempotencyKey'])) {
            $opts['idempotencyKey'] = $options['idempotencyKey'];
        }

        return $this->client->request('POST', '/numerology/pythagorean/balance', $opts);
    }

    /**
     * Birthday (pythagorean) (POST /numerology/pythagorean/birthday).
     *
     * @param array<string, mixed>|list<mixed>|object|null $body  Array, list, or DTO with `toArray()`.
     * @param array{headers?: array<string, string>, query?: array<string, scalar|array<int|string, scalar>>, idempotencyKey?: string} $options
     */
    public function pythagoreanBirthday(array|object|null $body = null, array $options = []): mixed
    {
        $opts = [];
        if ($body !== null) {
            $opts['json'] = $body;
        }
        if (!empty($options['query'])) {
            $opts['query'] = $options['query'];
        }
        if (!empty($options['headers'])) {
            $opts['headers'] = $options['headers'];
        }
        if (isset($options['idempotencyKey'])) {
            $opts['idempotencyKey'] = $options['idempotencyKey'];
        }

        return $this->client->request('POST', '/numerology/pythagorean/birthday', $opts);
    }

    /**
     * Challenge Cycles (pythagorean) (POST /numerology/pythagorean/challenge).
     *
     * @param array<string, mixed>|list<mixed>|object|null $body  Array, list, or DTO with `toArray()`.
     * @param array{headers?: array<string, string>, query?: array<string, scalar|array<int|string, scalar>>, idempotencyKey?: string} $options
     */
    public function pythagoreanChallenge(array|object|null $body = null, array $options = []): mixed
    {
        $opts = [];
        if ($body !== null) {
            $opts['json'] = $body;
        }
        if (!empty($options['query'])) {
            $opts['query'] = $options['query'];
        }
        if (!empty($options['headers'])) {
            $opts['headers'] = $options['headers'];
        }
        if (isset($options['idempotencyKey'])) {
            $opts['idempotencyKey'] = $options['idempotencyKey'];
        }

        return $this->client->request('POST', '/numerology/pythagorean/challenge', $opts);
    }

    /**
     * Expression / Destiny (pythagorean) (POST /numerology/pythagorean/expression).
     *
     * @param array<string, mixed>|list<mixed>|object|null $body  Array, list, or DTO with `toArray()`.
     * @param array{headers?: array<string, string>, query?: array<string, scalar|array<int|string, scalar>>, idempotencyKey?: string} $options
     */
    public function pythagoreanExpression(array|object|null $body = null, array $options = []): mixed
    {
        $opts = [];
        if ($body !== null) {
            $opts['json'] = $body;
        }
        if (!empty($options['query'])) {
            $opts['query'] = $options['query'];
        }
        if (!empty($options['headers'])) {
            $opts['headers'] = $options['headers'];
        }
        if (isset($options['idempotencyKey'])) {
            $opts['idempotencyKey'] = $options['idempotencyKey'];
        }

        return $this->client->request('POST', '/numerology/pythagorean/expression', $opts);
    }

    /**
     * Life Path Number (pythagorean) (POST /numerology/pythagorean/life-path).
     *
     * @param array<string, mixed>|list<mixed>|object|null $body  Array, list, or DTO with `toArray()`.
     * @param array{headers?: array<string, string>, query?: array<string, scalar|array<int|string, scalar>>, idempotencyKey?: string} $options
     */
    public function pythagoreanLifePath(array|object|null $body = null, array $options = []): mixed
    {
        $opts = [];
        if ($body !== null) {
            $opts['json'] = $body;
        }
        if (!empty($options['query'])) {
            $opts['query'] = $options['query'];
        }
        if (!empty($options['headers'])) {
            $opts['headers'] = $options['headers'];
        }
        if (isset($options['idempotencyKey'])) {
            $opts['idempotencyKey'] = $options['idempotencyKey'];
        }

        return $this->client->request('POST', '/numerology/pythagorean/life-path', $opts);
    }

    /**
     * Maturity (pythagorean) (POST /numerology/pythagorean/maturity).
     *
     * @param array<string, mixed>|list<mixed>|object|null $body  Array, list, or DTO with `toArray()`.
     * @param array{headers?: array<string, string>, query?: array<string, scalar|array<int|string, scalar>>, idempotencyKey?: string} $options
     */
    public function pythagoreanMaturity(array|object|null $body = null, array $options = []): mixed
    {
        $opts = [];
        if ($body !== null) {
            $opts['json'] = $body;
        }
        if (!empty($options['query'])) {
            $opts['query'] = $options['query'];
        }
        if (!empty($options['headers'])) {
            $opts['headers'] = $options['headers'];
        }
        if (isset($options['idempotencyKey'])) {
            $opts['idempotencyKey'] = $options['idempotencyKey'];
        }

        return $this->client->request('POST', '/numerology/pythagorean/maturity', $opts);
    }

    /**
     * Personal Year (pythagorean) (POST /numerology/pythagorean/personal-year).
     *
     * @param array<string, mixed>|list<mixed>|object|null $body  Array, list, or DTO with `toArray()`.
     * @param array{headers?: array<string, string>, query?: array<string, scalar|array<int|string, scalar>>, idempotencyKey?: string} $options
     */
    public function pythagoreanPersonalYear(array|object|null $body = null, array $options = []): mixed
    {
        $opts = [];
        if ($body !== null) {
            $opts['json'] = $body;
        }
        if (!empty($options['query'])) {
            $opts['query'] = $options['query'];
        }
        if (!empty($options['headers'])) {
            $opts['headers'] = $options['headers'];
        }
        if (isset($options['idempotencyKey'])) {
            $opts['idempotencyKey'] = $options['idempotencyKey'];
        }

        return $this->client->request('POST', '/numerology/pythagorean/personal-year', $opts);
    }

    /**
     * Personality (pythagorean) (POST /numerology/pythagorean/personality).
     *
     * @param array<string, mixed>|list<mixed>|object|null $body  Array, list, or DTO with `toArray()`.
     * @param array{headers?: array<string, string>, query?: array<string, scalar|array<int|string, scalar>>, idempotencyKey?: string} $options
     */
    public function pythagoreanPersonality(array|object|null $body = null, array $options = []): mixed
    {
        $opts = [];
        if ($body !== null) {
            $opts['json'] = $body;
        }
        if (!empty($options['query'])) {
            $opts['query'] = $options['query'];
        }
        if (!empty($options['headers'])) {
            $opts['headers'] = $options['headers'];
        }
        if (isset($options['idempotencyKey'])) {
            $opts['idempotencyKey'] = $options['idempotencyKey'];
        }

        return $this->client->request('POST', '/numerology/pythagorean/personality', $opts);
    }

    /**
     * Pinnacle Cycles (pythagorean) (POST /numerology/pythagorean/pinnacles).
     *
     * @param array<string, mixed>|list<mixed>|object|null $body  Array, list, or DTO with `toArray()`.
     * @param array{headers?: array<string, string>, query?: array<string, scalar|array<int|string, scalar>>, idempotencyKey?: string} $options
     */
    public function pythagoreanPinnacles(array|object|null $body = null, array $options = []): mixed
    {
        $opts = [];
        if ($body !== null) {
            $opts['json'] = $body;
        }
        if (!empty($options['query'])) {
            $opts['query'] = $options['query'];
        }
        if (!empty($options['headers'])) {
            $opts['headers'] = $options['headers'];
        }
        if (isset($options['idempotencyKey'])) {
            $opts['idempotencyKey'] = $options['idempotencyKey'];
        }

        return $this->client->request('POST', '/numerology/pythagorean/pinnacles', $opts);
    }

    /**
     * Soul Urge / Heart's Desire (pythagorean) (POST /numerology/pythagorean/soul-urge).
     *
     * @param array<string, mixed>|list<mixed>|object|null $body  Array, list, or DTO with `toArray()`.
     * @param array{headers?: array<string, string>, query?: array<string, scalar|array<int|string, scalar>>, idempotencyKey?: string} $options
     */
    public function pythagoreanSoulUrge(array|object|null $body = null, array $options = []): mixed
    {
        $opts = [];
        if ($body !== null) {
            $opts['json'] = $body;
        }
        if (!empty($options['query'])) {
            $opts['query'] = $options['query'];
        }
        if (!empty($options['headers'])) {
            $opts['headers'] = $options['headers'];
        }
        if (isset($options['idempotencyKey'])) {
            $opts['idempotencyKey'] = $options['idempotencyKey'];
        }

        return $this->client->request('POST', '/numerology/pythagorean/soul-urge', $opts);
    }

    /**
     * Balance (vedic) (POST /numerology/vedic/balance).
     *
     * @param array<string, mixed>|list<mixed>|object|null $body  Array, list, or DTO with `toArray()`.
     * @param array{headers?: array<string, string>, query?: array<string, scalar|array<int|string, scalar>>, idempotencyKey?: string} $options
     */
    public function vedicBalance(array|object|null $body = null, array $options = []): mixed
    {
        $opts = [];
        if ($body !== null) {
            $opts['json'] = $body;
        }
        if (!empty($options['query'])) {
            $opts['query'] = $options['query'];
        }
        if (!empty($options['headers'])) {
            $opts['headers'] = $options['headers'];
        }
        if (isset($options['idempotencyKey'])) {
            $opts['idempotencyKey'] = $options['idempotencyKey'];
        }

        return $this->client->request('POST', '/numerology/vedic/balance', $opts);
    }

    /**
     * Birthday (vedic) (POST /numerology/vedic/birthday).
     *
     * @param array<string, mixed>|list<mixed>|object|null $body  Array, list, or DTO with `toArray()`.
     * @param array{headers?: array<string, string>, query?: array<string, scalar|array<int|string, scalar>>, idempotencyKey?: string} $options
     */
    public function vedicBirthday(array|object|null $body = null, array $options = []): mixed
    {
        $opts = [];
        if ($body !== null) {
            $opts['json'] = $body;
        }
        if (!empty($options['query'])) {
            $opts['query'] = $options['query'];
        }
        if (!empty($options['headers'])) {
            $opts['headers'] = $options['headers'];
        }
        if (isset($options['idempotencyKey'])) {
            $opts['idempotencyKey'] = $options['idempotencyKey'];
        }

        return $this->client->request('POST', '/numerology/vedic/birthday', $opts);
    }

    /**
     * Challenge Cycles (vedic) (POST /numerology/vedic/challenge).
     *
     * @param array<string, mixed>|list<mixed>|object|null $body  Array, list, or DTO with `toArray()`.
     * @param array{headers?: array<string, string>, query?: array<string, scalar|array<int|string, scalar>>, idempotencyKey?: string} $options
     */
    public function vedicChallenge(array|object|null $body = null, array $options = []): mixed
    {
        $opts = [];
        if ($body !== null) {
            $opts['json'] = $body;
        }
        if (!empty($options['query'])) {
            $opts['query'] = $options['query'];
        }
        if (!empty($options['headers'])) {
            $opts['headers'] = $options['headers'];
        }
        if (isset($options['idempotencyKey'])) {
            $opts['idempotencyKey'] = $options['idempotencyKey'];
        }

        return $this->client->request('POST', '/numerology/vedic/challenge', $opts);
    }

    /**
     * Expression / Destiny (vedic) (POST /numerology/vedic/expression).
     *
     * @param array<string, mixed>|list<mixed>|object|null $body  Array, list, or DTO with `toArray()`.
     * @param array{headers?: array<string, string>, query?: array<string, scalar|array<int|string, scalar>>, idempotencyKey?: string} $options
     */
    public function vedicExpression(array|object|null $body = null, array $options = []): mixed
    {
        $opts = [];
        if ($body !== null) {
            $opts['json'] = $body;
        }
        if (!empty($options['query'])) {
            $opts['query'] = $options['query'];
        }
        if (!empty($options['headers'])) {
            $opts['headers'] = $options['headers'];
        }
        if (isset($options['idempotencyKey'])) {
            $opts['idempotencyKey'] = $options['idempotencyKey'];
        }

        return $this->client->request('POST', '/numerology/vedic/expression', $opts);
    }

    /**
     * Life Path Number (vedic) (POST /numerology/vedic/life-path).
     *
     * @param array<string, mixed>|list<mixed>|object|null $body  Array, list, or DTO with `toArray()`.
     * @param array{headers?: array<string, string>, query?: array<string, scalar|array<int|string, scalar>>, idempotencyKey?: string} $options
     */
    public function vedicLifePath(array|object|null $body = null, array $options = []): mixed
    {
        $opts = [];
        if ($body !== null) {
            $opts['json'] = $body;
        }
        if (!empty($options['query'])) {
            $opts['query'] = $options['query'];
        }
        if (!empty($options['headers'])) {
            $opts['headers'] = $options['headers'];
        }
        if (isset($options['idempotencyKey'])) {
            $opts['idempotencyKey'] = $options['idempotencyKey'];
        }

        return $this->client->request('POST', '/numerology/vedic/life-path', $opts);
    }

    /**
     * Maturity (vedic) (POST /numerology/vedic/maturity).
     *
     * @param array<string, mixed>|list<mixed>|object|null $body  Array, list, or DTO with `toArray()`.
     * @param array{headers?: array<string, string>, query?: array<string, scalar|array<int|string, scalar>>, idempotencyKey?: string} $options
     */
    public function vedicMaturity(array|object|null $body = null, array $options = []): mixed
    {
        $opts = [];
        if ($body !== null) {
            $opts['json'] = $body;
        }
        if (!empty($options['query'])) {
            $opts['query'] = $options['query'];
        }
        if (!empty($options['headers'])) {
            $opts['headers'] = $options['headers'];
        }
        if (isset($options['idempotencyKey'])) {
            $opts['idempotencyKey'] = $options['idempotencyKey'];
        }

        return $this->client->request('POST', '/numerology/vedic/maturity', $opts);
    }

    /**
     * Personal Year (vedic) (POST /numerology/vedic/personal-year).
     *
     * @param array<string, mixed>|list<mixed>|object|null $body  Array, list, or DTO with `toArray()`.
     * @param array{headers?: array<string, string>, query?: array<string, scalar|array<int|string, scalar>>, idempotencyKey?: string} $options
     */
    public function vedicPersonalYear(array|object|null $body = null, array $options = []): mixed
    {
        $opts = [];
        if ($body !== null) {
            $opts['json'] = $body;
        }
        if (!empty($options['query'])) {
            $opts['query'] = $options['query'];
        }
        if (!empty($options['headers'])) {
            $opts['headers'] = $options['headers'];
        }
        if (isset($options['idempotencyKey'])) {
            $opts['idempotencyKey'] = $options['idempotencyKey'];
        }

        return $this->client->request('POST', '/numerology/vedic/personal-year', $opts);
    }

    /**
     * Personality (vedic) (POST /numerology/vedic/personality).
     *
     * @param array<string, mixed>|list<mixed>|object|null $body  Array, list, or DTO with `toArray()`.
     * @param array{headers?: array<string, string>, query?: array<string, scalar|array<int|string, scalar>>, idempotencyKey?: string} $options
     */
    public function vedicPersonality(array|object|null $body = null, array $options = []): mixed
    {
        $opts = [];
        if ($body !== null) {
            $opts['json'] = $body;
        }
        if (!empty($options['query'])) {
            $opts['query'] = $options['query'];
        }
        if (!empty($options['headers'])) {
            $opts['headers'] = $options['headers'];
        }
        if (isset($options['idempotencyKey'])) {
            $opts['idempotencyKey'] = $options['idempotencyKey'];
        }

        return $this->client->request('POST', '/numerology/vedic/personality', $opts);
    }

    /**
     * Pinnacle Cycles (vedic) (POST /numerology/vedic/pinnacles).
     *
     * @param array<string, mixed>|list<mixed>|object|null $body  Array, list, or DTO with `toArray()`.
     * @param array{headers?: array<string, string>, query?: array<string, scalar|array<int|string, scalar>>, idempotencyKey?: string} $options
     */
    public function vedicPinnacles(array|object|null $body = null, array $options = []): mixed
    {
        $opts = [];
        if ($body !== null) {
            $opts['json'] = $body;
        }
        if (!empty($options['query'])) {
            $opts['query'] = $options['query'];
        }
        if (!empty($options['headers'])) {
            $opts['headers'] = $options['headers'];
        }
        if (isset($options['idempotencyKey'])) {
            $opts['idempotencyKey'] = $options['idempotencyKey'];
        }

        return $this->client->request('POST', '/numerology/vedic/pinnacles', $opts);
    }

    /**
     * Soul Urge / Heart's Desire (vedic) (POST /numerology/vedic/soul-urge).
     *
     * @param array<string, mixed>|list<mixed>|object|null $body  Array, list, or DTO with `toArray()`.
     * @param array{headers?: array<string, string>, query?: array<string, scalar|array<int|string, scalar>>, idempotencyKey?: string} $options
     */
    public function vedicSoulUrge(array|object|null $body = null, array $options = []): mixed
    {
        $opts = [];
        if ($body !== null) {
            $opts['json'] = $body;
        }
        if (!empty($options['query'])) {
            $opts['query'] = $options['query'];
        }
        if (!empty($options['headers'])) {
            $opts['headers'] = $options['headers'];
        }
        if (isset($options['idempotencyKey'])) {
            $opts['idempotencyKey'] = $options['idempotencyKey'];
        }

        return $this->client->request('POST', '/numerology/vedic/soul-urge', $opts);
    }
}
