<?php

declare(strict_types=1);

// AUTO-GENERATED by scripts/generate-namespaces.php — DO NOT EDIT.
// Run `composer generate:namespaces` to refresh from openapi.json.

namespace Astroway\Namespaces;

use Astroway\Astroway;

/** Service for reports.* endpoints. */
final class ReportsService
{
    public function __construct(private readonly Astroway $client)
    {
    }

    /**
     * AI Monthly Narrative (POST /reports/ai/monthly-narrative).
     *
     * @param array<string, mixed>|list<mixed>|object|null $body  Array, list, or DTO with `toArray()`.
     * @param array{headers?: array<string, string>, query?: array<string, scalar|array<int|string, scalar>>, idempotencyKey?: string} $options
     */
    public function aiMonthlyNarrative(array|object|null $body = null, array $options = []): mixed
    {
        $opts = [];
        if ($body !== null) {
            $opts['json'] = $body;
        }
        if (!empty($options['query'])) {
            $opts['query'] = $options['query'];
        }
        if (!empty($options['headers'])) {
            $opts['headers'] = $options['headers'];
        }
        if (isset($options['idempotencyKey'])) {
            $opts['idempotencyKey'] = $options['idempotencyKey'];
        }

        return $this->client->request('POST', '/reports/ai/monthly-narrative', $opts);
    }

    /**
     * AI Natal Narrative (POST /reports/ai/natal-narrative).
     *
     * @param array<string, mixed>|list<mixed>|object|null $body  Array, list, or DTO with `toArray()`.
     * @param array{headers?: array<string, string>, query?: array<string, scalar|array<int|string, scalar>>, idempotencyKey?: string} $options
     */
    public function aiNatalNarrative(array|object|null $body = null, array $options = []): mixed
    {
        $opts = [];
        if ($body !== null) {
            $opts['json'] = $body;
        }
        if (!empty($options['query'])) {
            $opts['query'] = $options['query'];
        }
        if (!empty($options['headers'])) {
            $opts['headers'] = $options['headers'];
        }
        if (isset($options['idempotencyKey'])) {
            $opts['idempotencyKey'] = $options['idempotencyKey'];
        }

        return $this->client->request('POST', '/reports/ai/natal-narrative', $opts);
    }

    /**
     * AI Synastry Narrative (POST /reports/ai/synastry-narrative).
     *
     * @param array<string, mixed>|list<mixed>|object|null $body  Array, list, or DTO with `toArray()`.
     * @param array{headers?: array<string, string>, query?: array<string, scalar|array<int|string, scalar>>, idempotencyKey?: string} $options
     */
    public function aiSynastryNarrative(array|object|null $body = null, array $options = []): mixed
    {
        $opts = [];
        if ($body !== null) {
            $opts['json'] = $body;
        }
        if (!empty($options['query'])) {
            $opts['query'] = $options['query'];
        }
        if (!empty($options['headers'])) {
            $opts['headers'] = $options['headers'];
        }
        if (isset($options['idempotencyKey'])) {
            $opts['idempotencyKey'] = $options['idempotencyKey'];
        }

        return $this->client->request('POST', '/reports/ai/synastry-narrative', $opts);
    }

    /**
     * AI Transit Narrative (single date) (POST /reports/ai/transit-narrative).
     *
     * @param array<string, mixed>|list<mixed>|object|null $body  Array, list, or DTO with `toArray()`.
     * @param array{headers?: array<string, string>, query?: array<string, scalar|array<int|string, scalar>>, idempotencyKey?: string} $options
     */
    public function aiTransitNarrative(array|object|null $body = null, array $options = []): mixed
    {
        $opts = [];
        if ($body !== null) {
            $opts['json'] = $body;
        }
        if (!empty($options['query'])) {
            $opts['query'] = $options['query'];
        }
        if (!empty($options['headers'])) {
            $opts['headers'] = $options['headers'];
        }
        if (isset($options['idempotencyKey'])) {
            $opts['idempotencyKey'] = $options['idempotencyKey'];
        }

        return $this->client->request('POST', '/reports/ai/transit-narrative', $opts);
    }

    /**
     * AI Year-Ahead Narrative (POST /reports/ai/year-ahead-narrative).
     *
     * @param array<string, mixed>|list<mixed>|object|null $body  Array, list, or DTO with `toArray()`.
     * @param array{headers?: array<string, string>, query?: array<string, scalar|array<int|string, scalar>>, idempotencyKey?: string} $options
     */
    public function aiYearAheadNarrative(array|object|null $body = null, array $options = []): mixed
    {
        $opts = [];
        if ($body !== null) {
            $opts['json'] = $body;
        }
        if (!empty($options['query'])) {
            $opts['query'] = $options['query'];
        }
        if (!empty($options['headers'])) {
            $opts['headers'] = $options['headers'];
        }
        if (isset($options['idempotencyKey'])) {
            $opts['idempotencyKey'] = $options['idempotencyKey'];
        }

        return $this->client->request('POST', '/reports/ai/year-ahead-narrative', $opts);
    }

    /**
     * Generate Business Astrology Report (PDF or HTML) (POST /reports/business).
     *
     * @param array<string, mixed>|list<mixed>|object|null $body  Array, list, or DTO with `toArray()`.
     * @param array{headers?: array<string, string>, query?: array<string, scalar|array<int|string, scalar>>, idempotencyKey?: string} $options
     */
    public function business(array|object|null $body = null, array $options = []): mixed
    {
        $opts = [];
        if ($body !== null) {
            $opts['json'] = $body;
        }
        if (!empty($options['query'])) {
            $opts['query'] = $options['query'];
        }
        if (!empty($options['headers'])) {
            $opts['headers'] = $options['headers'];
        }
        if (isset($options['idempotencyKey'])) {
            $opts['idempotencyKey'] = $options['idempotencyKey'];
        }

        return $this->client->request('POST', '/reports/business', $opts);
    }

    /**
     * Generate Career Compass Report (PDF or HTML) (POST /reports/career).
     *
     * @param array<string, mixed>|list<mixed>|object|null $body  Array, list, or DTO with `toArray()`.
     * @param array{headers?: array<string, string>, query?: array<string, scalar|array<int|string, scalar>>, idempotencyKey?: string} $options
     */
    public function career(array|object|null $body = null, array $options = []): mixed
    {
        $opts = [];
        if ($body !== null) {
            $opts['json'] = $body;
        }
        if (!empty($options['query'])) {
            $opts['query'] = $options['query'];
        }
        if (!empty($options['headers'])) {
            $opts['headers'] = $options['headers'];
        }
        if (isset($options['idempotencyKey'])) {
            $opts['idempotencyKey'] = $options['idempotencyKey'];
        }

        return $this->client->request('POST', '/reports/career', $opts);
    }

    /**
     * Generate Child Astrology Report (PDF or HTML) (POST /reports/child).
     *
     * @param array<string, mixed>|list<mixed>|object|null $body  Array, list, or DTO with `toArray()`.
     * @param array{headers?: array<string, string>, query?: array<string, scalar|array<int|string, scalar>>, idempotencyKey?: string} $options
     */
    public function child(array|object|null $body = null, array $options = []): mixed
    {
        $opts = [];
        if ($body !== null) {
            $opts['json'] = $body;
        }
        if (!empty($options['query'])) {
            $opts['query'] = $options['query'];
        }
        if (!empty($options['headers'])) {
            $opts['headers'] = $options['headers'];
        }
        if (isset($options['idempotencyKey'])) {
            $opts['idempotencyKey'] = $options['idempotencyKey'];
        }

        return $this->client->request('POST', '/reports/child', $opts);
    }

    /**
     * Generate Report — Unified Dispatcher (V2) (POST /reports/generate).
     *
     * @param array<string, mixed>|list<mixed>|object|null $body  Array, list, or DTO with `toArray()`.
     * @param array{headers?: array<string, string>, query?: array<string, scalar|array<int|string, scalar>>, idempotencyKey?: string} $options
     */
    public function generate(array|object|null $body = null, array $options = []): mixed
    {
        $opts = [];
        if ($body !== null) {
            $opts['json'] = $body;
        }
        if (!empty($options['query'])) {
            $opts['query'] = $options['query'];
        }
        if (!empty($options['headers'])) {
            $opts['headers'] = $options['headers'];
        }
        if (isset($options['idempotencyKey'])) {
            $opts['idempotencyKey'] = $options['idempotencyKey'];
        }

        return $this->client->request('POST', '/reports/generate', $opts);
    }

    /**
     * Generate Human Design Report (PDF or HTML) (POST /reports/human-design).
     *
     * @param array<string, mixed>|list<mixed>|object|null $body  Array, list, or DTO with `toArray()`.
     * @param array{headers?: array<string, string>, query?: array<string, scalar|array<int|string, scalar>>, idempotencyKey?: string} $options
     */
    public function humanDesign(array|object|null $body = null, array $options = []): mixed
    {
        $opts = [];
        if ($body !== null) {
            $opts['json'] = $body;
        }
        if (!empty($options['query'])) {
            $opts['query'] = $options['query'];
        }
        if (!empty($options['headers'])) {
            $opts['headers'] = $options['headers'];
        }
        if (isset($options['idempotencyKey'])) {
            $opts['idempotencyKey'] = $options['idempotencyKey'];
        }

        return $this->client->request('POST', '/reports/human-design', $opts);
    }

    /**
     * Generate Lal Kitab Report (PDF or HTML) (POST /reports/lal-kitab).
     *
     * @param array<string, mixed>|list<mixed>|object|null $body  Array, list, or DTO with `toArray()`.
     * @param array{headers?: array<string, string>, query?: array<string, scalar|array<int|string, scalar>>, idempotencyKey?: string} $options
     */
    public function lalKitab(array|object|null $body = null, array $options = []): mixed
    {
        $opts = [];
        if ($body !== null) {
            $opts['json'] = $body;
        }
        if (!empty($options['query'])) {
            $opts['query'] = $options['query'];
        }
        if (!empty($options['headers'])) {
            $opts['headers'] = $options['headers'];
        }
        if (isset($options['idempotencyKey'])) {
            $opts['idempotencyKey'] = $options['idempotencyKey'];
        }

        return $this->client->request('POST', '/reports/lal-kitab', $opts);
    }

    /**
     * Generate Love Report (PDF or HTML) (POST /reports/love).
     *
     * @param array<string, mixed>|list<mixed>|object|null $body  Array, list, or DTO with `toArray()`.
     * @param array{headers?: array<string, string>, query?: array<string, scalar|array<int|string, scalar>>, idempotencyKey?: string} $options
     */
    public function love(array|object|null $body = null, array $options = []): mixed
    {
        $opts = [];
        if ($body !== null) {
            $opts['json'] = $body;
        }
        if (!empty($options['query'])) {
            $opts['query'] = $options['query'];
        }
        if (!empty($options['headers'])) {
            $opts['headers'] = $options['headers'];
        }
        if (isset($options['idempotencyKey'])) {
            $opts['idempotencyKey'] = $options['idempotencyKey'];
        }

        return $this->client->request('POST', '/reports/love', $opts);
    }

    /**
     * Generate Money Report (PDF or HTML) (POST /reports/money).
     *
     * @param array<string, mixed>|list<mixed>|object|null $body  Array, list, or DTO with `toArray()`.
     * @param array{headers?: array<string, string>, query?: array<string, scalar|array<int|string, scalar>>, idempotencyKey?: string} $options
     */
    public function money(array|object|null $body = null, array $options = []): mixed
    {
        $opts = [];
        if ($body !== null) {
            $opts['json'] = $body;
        }
        if (!empty($options['query'])) {
            $opts['query'] = $options['query'];
        }
        if (!empty($options['headers'])) {
            $opts['headers'] = $options['headers'];
        }
        if (isset($options['idempotencyKey'])) {
            $opts['idempotencyKey'] = $options['idempotencyKey'];
        }

        return $this->client->request('POST', '/reports/money', $opts);
    }

    /**
     * Generate Muhurta Report (PDF or HTML) (POST /reports/muhurta).
     *
     * @param array<string, mixed>|list<mixed>|object|null $body  Array, list, or DTO with `toArray()`.
     * @param array{headers?: array<string, string>, query?: array<string, scalar|array<int|string, scalar>>, idempotencyKey?: string} $options
     */
    public function muhurta(array|object|null $body = null, array $options = []): mixed
    {
        $opts = [];
        if ($body !== null) {
            $opts['json'] = $body;
        }
        if (!empty($options['query'])) {
            $opts['query'] = $options['query'];
        }
        if (!empty($options['headers'])) {
            $opts['headers'] = $options['headers'];
        }
        if (isset($options['idempotencyKey'])) {
            $opts['idempotencyKey'] = $options['idempotencyKey'];
        }

        return $this->client->request('POST', '/reports/muhurta', $opts);
    }

    /**
     * Generate Natal Report (PDF or HTML) (POST /reports/natal).
     *
     * @param array<string, mixed>|list<mixed>|object|null $body  Array, list, or DTO with `toArray()`.
     * @param array{headers?: array<string, string>, query?: array<string, scalar|array<int|string, scalar>>, idempotencyKey?: string} $options
     */
    public function natal(array|object|null $body = null, array $options = []): mixed
    {
        $opts = [];
        if ($body !== null) {
            $opts['json'] = $body;
        }
        if (!empty($options['query'])) {
            $opts['query'] = $options['query'];
        }
        if (!empty($options['headers'])) {
            $opts['headers'] = $options['headers'];
        }
        if (isset($options['idempotencyKey'])) {
            $opts['idempotencyKey'] = $options['idempotencyKey'];
        }

        return $this->client->request('POST', '/reports/natal', $opts);
    }

    /**
     * Generate Stellaforge Birth-Chart Poster (PDF or HTML) (POST /reports/stellaforge).
     *
     * @param array<string, mixed>|list<mixed>|object|null $body  Array, list, or DTO with `toArray()`.
     * @param array{headers?: array<string, string>, query?: array<string, scalar|array<int|string, scalar>>, idempotencyKey?: string} $options
     */
    public function stellaforge(array|object|null $body = null, array $options = []): mixed
    {
        $opts = [];
        if ($body !== null) {
            $opts['json'] = $body;
        }
        if (!empty($options['query'])) {
            $opts['query'] = $options['query'];
        }
        if (!empty($options['headers'])) {
            $opts['headers'] = $options['headers'];
        }
        if (isset($options['idempotencyKey'])) {
            $opts['idempotencyKey'] = $options['idempotencyKey'];
        }

        return $this->client->request('POST', '/reports/stellaforge', $opts);
    }

    /**
     * Generate Synastry Report (PDF or HTML) (POST /reports/synastry).
     *
     * @param array<string, mixed>|list<mixed>|object|null $body  Array, list, or DTO with `toArray()`.
     * @param array{headers?: array<string, string>, query?: array<string, scalar|array<int|string, scalar>>, idempotencyKey?: string} $options
     */
    public function synastry(array|object|null $body = null, array $options = []): mixed
    {
        $opts = [];
        if ($body !== null) {
            $opts['json'] = $body;
        }
        if (!empty($options['query'])) {
            $opts['query'] = $options['query'];
        }
        if (!empty($options['headers'])) {
            $opts['headers'] = $options['headers'];
        }
        if (isset($options['idempotencyKey'])) {
            $opts['idempotencyKey'] = $options['idempotencyKey'];
        }

        return $this->client->request('POST', '/reports/synastry', $opts);
    }

    /**
     * Generate Tarot Reading (PDF or HTML) (POST /reports/tarot).
     *
     * @param array<string, mixed>|list<mixed>|object|null $body  Array, list, or DTO with `toArray()`.
     * @param array{headers?: array<string, string>, query?: array<string, scalar|array<int|string, scalar>>, idempotencyKey?: string} $options
     */
    public function tarot(array|object|null $body = null, array $options = []): mixed
    {
        $opts = [];
        if ($body !== null) {
            $opts['json'] = $body;
        }
        if (!empty($options['query'])) {
            $opts['query'] = $options['query'];
        }
        if (!empty($options['headers'])) {
            $opts['headers'] = $options['headers'];
        }
        if (isset($options['idempotencyKey'])) {
            $opts['idempotencyKey'] = $options['idempotencyKey'];
        }

        return $this->client->request('POST', '/reports/tarot', $opts);
    }

    /**
     * Generate Year-Ahead Transit (PDF or HTML) (POST /reports/transit-yearly).
     *
     * @param array<string, mixed>|list<mixed>|object|null $body  Array, list, or DTO with `toArray()`.
     * @param array{headers?: array<string, string>, query?: array<string, scalar|array<int|string, scalar>>, idempotencyKey?: string} $options
     */
    public function transitYearly(array|object|null $body = null, array $options = []): mixed
    {
        $opts = [];
        if ($body !== null) {
            $opts['json'] = $body;
        }
        if (!empty($options['query'])) {
            $opts['query'] = $options['query'];
        }
        if (!empty($options['headers'])) {
            $opts['headers'] = $options['headers'];
        }
        if (isset($options['idempotencyKey'])) {
            $opts['idempotencyKey'] = $options['idempotencyKey'];
        }

        return $this->client->request('POST', '/reports/transit-yearly', $opts);
    }

    /**
     * Generate Vedic Kundli (PDF or HTML) (POST /reports/vedic-kundli).
     *
     * @param array<string, mixed>|list<mixed>|object|null $body  Array, list, or DTO with `toArray()`.
     * @param array{headers?: array<string, string>, query?: array<string, scalar|array<int|string, scalar>>, idempotencyKey?: string} $options
     */
    public function vedicKundli(array|object|null $body = null, array $options = []): mixed
    {
        $opts = [];
        if ($body !== null) {
            $opts['json'] = $body;
        }
        if (!empty($options['query'])) {
            $opts['query'] = $options['query'];
        }
        if (!empty($options['headers'])) {
            $opts['headers'] = $options['headers'];
        }
        if (isset($options['idempotencyKey'])) {
            $opts['idempotencyKey'] = $options['idempotencyKey'];
        }

        return $this->client->request('POST', '/reports/vedic-kundli', $opts);
    }
}
