<?php

declare(strict_types=1);

// AUTO-GENERATED by scripts/generate-namespaces.php — DO NOT EDIT.
// Run `composer generate:namespaces` to refresh from openapi.json.

namespace Astroway\Namespaces;

use Astroway\Astroway;

/** Service for ziwei.* endpoints. */
final class ZiweiService
{
    public function __construct(private readonly Astroway $client)
    {
    }

    /**
     * Full Chart (MVP) (POST /ziwei/full-chart).
     *
     * @param array<string, mixed>|list<mixed>|object|null $body  Array, list, or DTO with `toArray()`.
     * @param array{headers?: array<string, string>, query?: array<string, scalar|array<int|string, scalar>>, idempotencyKey?: string} $options
     */
    public function fullChart(array|object|null $body = null, array $options = []): mixed
    {
        $opts = [];
        if ($body !== null) {
            $opts['json'] = $body;
        }
        if (!empty($options['query'])) {
            $opts['query'] = $options['query'];
        }
        if (!empty($options['headers'])) {
            $opts['headers'] = $options['headers'];
        }
        if (isset($options['idempotencyKey'])) {
            $opts['idempotencyKey'] = $options['idempotencyKey'];
        }

        return $this->client->request('POST', '/ziwei/full-chart', $opts);
    }

    /**
     * 14 Main Stars (POST /ziwei/main-stars).
     *
     * @param array<string, mixed>|list<mixed>|object|null $body  Array, list, or DTO with `toArray()`.
     * @param array{headers?: array<string, string>, query?: array<string, scalar|array<int|string, scalar>>, idempotencyKey?: string} $options
     */
    public function mainStars(array|object|null $body = null, array $options = []): mixed
    {
        $opts = [];
        if ($body !== null) {
            $opts['json'] = $body;
        }
        if (!empty($options['query'])) {
            $opts['query'] = $options['query'];
        }
        if (!empty($options['headers'])) {
            $opts['headers'] = $options['headers'];
        }
        if (isset($options['idempotencyKey'])) {
            $opts['idempotencyKey'] = $options['idempotencyKey'];
        }

        return $this->client->request('POST', '/ziwei/main-stars', $opts);
    }

    /**
     * Career Palace (Guanlu) (POST /ziwei/palace-career).
     *
     * @param array<string, mixed>|list<mixed>|object|null $body  Array, list, or DTO with `toArray()`.
     * @param array{headers?: array<string, string>, query?: array<string, scalar|array<int|string, scalar>>, idempotencyKey?: string} $options
     */
    public function palaceCareer(array|object|null $body = null, array $options = []): mixed
    {
        $opts = [];
        if ($body !== null) {
            $opts['json'] = $body;
        }
        if (!empty($options['query'])) {
            $opts['query'] = $options['query'];
        }
        if (!empty($options['headers'])) {
            $opts['headers'] = $options['headers'];
        }
        if (isset($options['idempotencyKey'])) {
            $opts['idempotencyKey'] = $options['idempotencyKey'];
        }

        return $this->client->request('POST', '/ziwei/palace-career', $opts);
    }

    /**
     * Children Palace (Zinu) (POST /ziwei/palace-children).
     *
     * @param array<string, mixed>|list<mixed>|object|null $body  Array, list, or DTO with `toArray()`.
     * @param array{headers?: array<string, string>, query?: array<string, scalar|array<int|string, scalar>>, idempotencyKey?: string} $options
     */
    public function palaceChildren(array|object|null $body = null, array $options = []): mixed
    {
        $opts = [];
        if ($body !== null) {
            $opts['json'] = $body;
        }
        if (!empty($options['query'])) {
            $opts['query'] = $options['query'];
        }
        if (!empty($options['headers'])) {
            $opts['headers'] = $options['headers'];
        }
        if (isset($options['idempotencyKey'])) {
            $opts['idempotencyKey'] = $options['idempotencyKey'];
        }

        return $this->client->request('POST', '/ziwei/palace-children', $opts);
    }

    /**
     * Destiny Palace (Ming) (POST /ziwei/palace-destiny).
     *
     * @param array<string, mixed>|list<mixed>|object|null $body  Array, list, or DTO with `toArray()`.
     * @param array{headers?: array<string, string>, query?: array<string, scalar|array<int|string, scalar>>, idempotencyKey?: string} $options
     */
    public function palaceDestiny(array|object|null $body = null, array $options = []): mixed
    {
        $opts = [];
        if ($body !== null) {
            $opts['json'] = $body;
        }
        if (!empty($options['query'])) {
            $opts['query'] = $options['query'];
        }
        if (!empty($options['headers'])) {
            $opts['headers'] = $options['headers'];
        }
        if (isset($options['idempotencyKey'])) {
            $opts['idempotencyKey'] = $options['idempotencyKey'];
        }

        return $this->client->request('POST', '/ziwei/palace-destiny', $opts);
    }

    /**
     * Health Palace (Jie\'e) (POST /ziwei/palace-health).
     *
     * @param array<string, mixed>|list<mixed>|object|null $body  Array, list, or DTO with `toArray()`.
     * @param array{headers?: array<string, string>, query?: array<string, scalar|array<int|string, scalar>>, idempotencyKey?: string} $options
     */
    public function palaceHealth(array|object|null $body = null, array $options = []): mixed
    {
        $opts = [];
        if ($body !== null) {
            $opts['json'] = $body;
        }
        if (!empty($options['query'])) {
            $opts['query'] = $options['query'];
        }
        if (!empty($options['headers'])) {
            $opts['headers'] = $options['headers'];
        }
        if (isset($options['idempotencyKey'])) {
            $opts['idempotencyKey'] = $options['idempotencyKey'];
        }

        return $this->client->request('POST', '/ziwei/palace-health', $opts);
    }

    /**
     * Property Palace (Tianzhai) (POST /ziwei/palace-property).
     *
     * @param array<string, mixed>|list<mixed>|object|null $body  Array, list, or DTO with `toArray()`.
     * @param array{headers?: array<string, string>, query?: array<string, scalar|array<int|string, scalar>>, idempotencyKey?: string} $options
     */
    public function palaceProperty(array|object|null $body = null, array $options = []): mixed
    {
        $opts = [];
        if ($body !== null) {
            $opts['json'] = $body;
        }
        if (!empty($options['query'])) {
            $opts['query'] = $options['query'];
        }
        if (!empty($options['headers'])) {
            $opts['headers'] = $options['headers'];
        }
        if (isset($options['idempotencyKey'])) {
            $opts['idempotencyKey'] = $options['idempotencyKey'];
        }

        return $this->client->request('POST', '/ziwei/palace-property', $opts);
    }

    /**
     * Siblings Palace (Xiongdi) (POST /ziwei/palace-siblings).
     *
     * @param array<string, mixed>|list<mixed>|object|null $body  Array, list, or DTO with `toArray()`.
     * @param array{headers?: array<string, string>, query?: array<string, scalar|array<int|string, scalar>>, idempotencyKey?: string} $options
     */
    public function palaceSiblings(array|object|null $body = null, array $options = []): mixed
    {
        $opts = [];
        if ($body !== null) {
            $opts['json'] = $body;
        }
        if (!empty($options['query'])) {
            $opts['query'] = $options['query'];
        }
        if (!empty($options['headers'])) {
            $opts['headers'] = $options['headers'];
        }
        if (isset($options['idempotencyKey'])) {
            $opts['idempotencyKey'] = $options['idempotencyKey'];
        }

        return $this->client->request('POST', '/ziwei/palace-siblings', $opts);
    }

    /**
     * Spouse Palace (Fuqi) (POST /ziwei/palace-spouse).
     *
     * @param array<string, mixed>|list<mixed>|object|null $body  Array, list, or DTO with `toArray()`.
     * @param array{headers?: array<string, string>, query?: array<string, scalar|array<int|string, scalar>>, idempotencyKey?: string} $options
     */
    public function palaceSpouse(array|object|null $body = null, array $options = []): mixed
    {
        $opts = [];
        if ($body !== null) {
            $opts['json'] = $body;
        }
        if (!empty($options['query'])) {
            $opts['query'] = $options['query'];
        }
        if (!empty($options['headers'])) {
            $opts['headers'] = $options['headers'];
        }
        if (isset($options['idempotencyKey'])) {
            $opts['idempotencyKey'] = $options['idempotencyKey'];
        }

        return $this->client->request('POST', '/ziwei/palace-spouse', $opts);
    }

    /**
     * Travel Palace (Qianyi) (POST /ziwei/palace-travel).
     *
     * @param array<string, mixed>|list<mixed>|object|null $body  Array, list, or DTO with `toArray()`.
     * @param array{headers?: array<string, string>, query?: array<string, scalar|array<int|string, scalar>>, idempotencyKey?: string} $options
     */
    public function palaceTravel(array|object|null $body = null, array $options = []): mixed
    {
        $opts = [];
        if ($body !== null) {
            $opts['json'] = $body;
        }
        if (!empty($options['query'])) {
            $opts['query'] = $options['query'];
        }
        if (!empty($options['headers'])) {
            $opts['headers'] = $options['headers'];
        }
        if (isset($options['idempotencyKey'])) {
            $opts['idempotencyKey'] = $options['idempotencyKey'];
        }

        return $this->client->request('POST', '/ziwei/palace-travel', $opts);
    }

    /**
     * Wealth Palace (Caibo) (POST /ziwei/palace-wealth).
     *
     * @param array<string, mixed>|list<mixed>|object|null $body  Array, list, or DTO with `toArray()`.
     * @param array{headers?: array<string, string>, query?: array<string, scalar|array<int|string, scalar>>, idempotencyKey?: string} $options
     */
    public function palaceWealth(array|object|null $body = null, array $options = []): mixed
    {
        $opts = [];
        if ($body !== null) {
            $opts['json'] = $body;
        }
        if (!empty($options['query'])) {
            $opts['query'] = $options['query'];
        }
        if (!empty($options['headers'])) {
            $opts['headers'] = $options['headers'];
        }
        if (isset($options['idempotencyKey'])) {
            $opts['idempotencyKey'] = $options['idempotencyKey'];
        }

        return $this->client->request('POST', '/ziwei/palace-wealth', $opts);
    }

    /**
     * 12 Palaces (POST /ziwei/twelve-palaces).
     *
     * @param array<string, mixed>|list<mixed>|object|null $body  Array, list, or DTO with `toArray()`.
     * @param array{headers?: array<string, string>, query?: array<string, scalar|array<int|string, scalar>>, idempotencyKey?: string} $options
     */
    public function twelvePalaces(array|object|null $body = null, array $options = []): mixed
    {
        $opts = [];
        if ($body !== null) {
            $opts['json'] = $body;
        }
        if (!empty($options['query'])) {
            $opts['query'] = $options['query'];
        }
        if (!empty($options['headers'])) {
            $opts['headers'] = $options['headers'];
        }
        if (isset($options['idempotencyKey'])) {
            $opts['idempotencyKey'] = $options['idempotencyKey'];
        }

        return $this->client->request('POST', '/ziwei/twelve-palaces', $opts);
    }
}
