<?php

declare(strict_types=1);

// AUTO-GENERATED by scripts/generate-namespaces.php — DO NOT EDIT.
// Run `composer generate:namespaces` to refresh from openapi.json.

namespace Astroway\Namespaces;

use Astroway\Astroway;

/** Service for zodiac.* endpoints. */
final class ZodiacService
{
    public function __construct(private readonly Astroway $client)
    {
    }

    /**
     * Aquarius — Fixed Air (GET /zodiac/aquarius).
     *
     * @param array{headers?: array<string, string>, query?: array<string, scalar|array<int|string, scalar>>} $options
     */
    public function aquariusGet(array $options = []): mixed
    {
        $opts = [];
        if (!empty($options['query'])) {
            $opts['query'] = $options['query'];
        }
        if (!empty($options['headers'])) {
            $opts['headers'] = $options['headers'];
        }

        return $this->client->request('GET', '/zodiac/aquarius', $opts);
    }

    /**
     * Aries — Cardinal Fire (GET /zodiac/aries).
     *
     * @param array{headers?: array<string, string>, query?: array<string, scalar|array<int|string, scalar>>} $options
     */
    public function ariesGet(array $options = []): mixed
    {
        $opts = [];
        if (!empty($options['query'])) {
            $opts['query'] = $options['query'];
        }
        if (!empty($options['headers'])) {
            $opts['headers'] = $options['headers'];
        }

        return $this->client->request('GET', '/zodiac/aries', $opts);
    }

    /**
     * Cancer — Cardinal Water (GET /zodiac/cancer).
     *
     * @param array{headers?: array<string, string>, query?: array<string, scalar|array<int|string, scalar>>} $options
     */
    public function cancerGet(array $options = []): mixed
    {
        $opts = [];
        if (!empty($options['query'])) {
            $opts['query'] = $options['query'];
        }
        if (!empty($options['headers'])) {
            $opts['headers'] = $options['headers'];
        }

        return $this->client->request('GET', '/zodiac/cancer', $opts);
    }

    /**
     * Capricorn — Cardinal Earth (GET /zodiac/capricorn).
     *
     * @param array{headers?: array<string, string>, query?: array<string, scalar|array<int|string, scalar>>} $options
     */
    public function capricornGet(array $options = []): mixed
    {
        $opts = [];
        if (!empty($options['query'])) {
            $opts['query'] = $options['query'];
        }
        if (!empty($options['headers'])) {
            $opts['headers'] = $options['headers'];
        }

        return $this->client->request('GET', '/zodiac/capricorn', $opts);
    }

    /**
     * Gemini — Mutable Air (GET /zodiac/gemini).
     *
     * @param array{headers?: array<string, string>, query?: array<string, scalar|array<int|string, scalar>>} $options
     */
    public function geminiGet(array $options = []): mixed
    {
        $opts = [];
        if (!empty($options['query'])) {
            $opts['query'] = $options['query'];
        }
        if (!empty($options['headers'])) {
            $opts['headers'] = $options['headers'];
        }

        return $this->client->request('GET', '/zodiac/gemini', $opts);
    }

    /**
     * Leo — Fixed Fire (GET /zodiac/leo).
     *
     * @param array{headers?: array<string, string>, query?: array<string, scalar|array<int|string, scalar>>} $options
     */
    public function leoGet(array $options = []): mixed
    {
        $opts = [];
        if (!empty($options['query'])) {
            $opts['query'] = $options['query'];
        }
        if (!empty($options['headers'])) {
            $opts['headers'] = $options['headers'];
        }

        return $this->client->request('GET', '/zodiac/leo', $opts);
    }

    /**
     * Libra — Cardinal Air (GET /zodiac/libra).
     *
     * @param array{headers?: array<string, string>, query?: array<string, scalar|array<int|string, scalar>>} $options
     */
    public function libraGet(array $options = []): mixed
    {
        $opts = [];
        if (!empty($options['query'])) {
            $opts['query'] = $options['query'];
        }
        if (!empty($options['headers'])) {
            $opts['headers'] = $options['headers'];
        }

        return $this->client->request('GET', '/zodiac/libra', $opts);
    }

    /**
     * Pisces — Mutable Water (GET /zodiac/pisces).
     *
     * @param array{headers?: array<string, string>, query?: array<string, scalar|array<int|string, scalar>>} $options
     */
    public function piscesGet(array $options = []): mixed
    {
        $opts = [];
        if (!empty($options['query'])) {
            $opts['query'] = $options['query'];
        }
        if (!empty($options['headers'])) {
            $opts['headers'] = $options['headers'];
        }

        return $this->client->request('GET', '/zodiac/pisces', $opts);
    }

    /**
     * Sagittarius — Mutable Fire (GET /zodiac/sagittarius).
     *
     * @param array{headers?: array<string, string>, query?: array<string, scalar|array<int|string, scalar>>} $options
     */
    public function sagittariusGet(array $options = []): mixed
    {
        $opts = [];
        if (!empty($options['query'])) {
            $opts['query'] = $options['query'];
        }
        if (!empty($options['headers'])) {
            $opts['headers'] = $options['headers'];
        }

        return $this->client->request('GET', '/zodiac/sagittarius', $opts);
    }

    /**
     * Scorpio — Fixed Water (GET /zodiac/scorpio).
     *
     * @param array{headers?: array<string, string>, query?: array<string, scalar|array<int|string, scalar>>} $options
     */
    public function scorpioGet(array $options = []): mixed
    {
        $opts = [];
        if (!empty($options['query'])) {
            $opts['query'] = $options['query'];
        }
        if (!empty($options['headers'])) {
            $opts['headers'] = $options['headers'];
        }

        return $this->client->request('GET', '/zodiac/scorpio', $opts);
    }

    /**
     * Taurus — Fixed Earth (GET /zodiac/taurus).
     *
     * @param array{headers?: array<string, string>, query?: array<string, scalar|array<int|string, scalar>>} $options
     */
    public function taurusGet(array $options = []): mixed
    {
        $opts = [];
        if (!empty($options['query'])) {
            $opts['query'] = $options['query'];
        }
        if (!empty($options['headers'])) {
            $opts['headers'] = $options['headers'];
        }

        return $this->client->request('GET', '/zodiac/taurus', $opts);
    }

    /**
     * Virgo — Mutable Earth (GET /zodiac/virgo).
     *
     * @param array{headers?: array<string, string>, query?: array<string, scalar|array<int|string, scalar>>} $options
     */
    public function virgoGet(array $options = []): mixed
    {
        $opts = [];
        if (!empty($options['query'])) {
            $opts['query'] = $options['query'];
        }
        if (!empty($options['headers'])) {
            $opts['headers'] = $options['headers'];
        }

        return $this->client->request('GET', '/zodiac/virgo', $opts);
    }
}
