<?php

declare(strict_types=1);

// AUTO-GENERATED by scripts/generate-namespaces.php — DO NOT EDIT.
// Run `composer generate:namespaces` to refresh from openapi.json.

namespace Astroway;

use Astroway\Namespaces\AcgService;
use Astroway\Namespaces\AcgZonesService;
use Astroway\Namespaces\AiService;
use Astroway\Namespaces\AlgolMinimumService;
use Astroway\Namespaces\AlmutenService;
use Astroway\Namespaces\AntisciaService;
use Astroway\Namespaces\ArabicPartsService;
use Astroway\Namespaces\AshtakavargaService;
use Astroway\Namespaces\AspectBarService;
use Astroway\Namespaces\AspectTimelineService;
use Astroway\Namespaces\AspectsService;
use Astroway\Namespaces\BaziService;
use Astroway\Namespaces\BusinessService;
use Astroway\Namespaces\CcgAnalysisService;
use Astroway\Namespaces\ChartService;
use Astroway\Namespaces\ChineseService;
use Astroway\Namespaces\CoalescentService;
use Astroway\Namespaces\CompositeService;
use Astroway\Namespaces\CosmobiologyService;
use Astroway\Namespaces\CyclicIndexService;
use Astroway\Namespaces\DavisonService;
use Astroway\Namespaces\DestinyMatrixService;
use Astroway\Namespaces\DispositionChainsService;
use Astroway\Namespaces\DjamaspaService;
use Astroway\Namespaces\DraconicService;
use Astroway\Namespaces\EclipseAnalysisService;
use Astroway\Namespaces\EclipsesService;
use Astroway\Namespaces\EphemerisService;
use Astroway\Namespaces\EsotericService;
use Astroway\Namespaces\EssentialDignitiesService;
use Astroway\Namespaces\EvolutionaryService;
use Astroway\Namespaces\FamilyService;
use Astroway\Namespaces\FinancialService;
use Astroway\Namespaces\FirdariaService;
use Astroway\Namespaces\FixedStarsService;
use Astroway\Namespaces\ForecastCalendarService;
use Astroway\Namespaces\GauquelinSectorsService;
use Astroway\Namespaces\GeodeticService;
use Astroway\Namespaces\GeomancyService;
use Astroway\Namespaces\GroupSynastryService;
use Astroway\Namespaces\HarmonicsService;
use Astroway\Namespaces\HdService;
use Astroway\Namespaces\HeliocentricService;
use Astroway\Namespaces\HellenisticService;
use Astroway\Namespaces\HoraryService;
use Astroway\Namespaces\HorizonService;
use Astroway\Namespaces\HoroscopeService;
use Astroway\Namespaces\HousesService;
use Astroway\Namespaces\HumanDesignService;
use Astroway\Namespaces\HylegService;
use Astroway\Namespaces\IchingService;
use Astroway\Namespaces\IngressesService;
use Astroway\Namespaces\InterpretService;
use Astroway\Namespaces\LocalSpaceService;
use Astroway\Namespaces\LunarCalendarService;
use Astroway\Namespaces\LunarReturnService;
use Astroway\Namespaces\Match_Service;
use Astroway\Namespaces\MayanService;
use Astroway\Namespaces\McpService;
use Astroway\Namespaces\MidpointTreesService;
use Astroway\Namespaces\MidpointsService;
use Astroway\Namespaces\MinorProgressionsService;
use Astroway\Namespaces\ModernService;
use Astroway\Namespaces\MoonAspectsService;
use Astroway\Namespaces\MoonPhaseService;
use Astroway\Namespaces\MoonVocService;
use Astroway\Namespaces\MuhurtaService;
use Astroway\Namespaces\NakshatrasService;
use Astroway\Namespaces\NumerologyService;
use Astroway\Namespaces\PalmistryService;
use Astroway\Namespaces\ParallelAspectsService;
use Astroway\Namespaces\ParansService;
use Astroway\Namespaces\PetService;
use Astroway\Namespaces\PhaseReturnService;
use Astroway\Namespaces\PlanetaryCyclesService;
use Astroway\Namespaces\PlanetaryHoursService;
use Astroway\Namespaces\PlanetaryPhasesService;
use Astroway\Namespaces\PlanetaryReturnService;
use Astroway\Namespaces\PlanetsService;
use Astroway\Namespaces\PrimaryDirectionsService;
use Astroway\Namespaces\ProfectionsService;
use Astroway\Namespaces\ProgressionsService;
use Astroway\Namespaces\ReceptionsService;
use Astroway\Namespaces\RectificationService;
use Astroway\Namespaces\ReferenceService;
use Astroway\Namespaces\RelocationService;
use Astroway\Namespaces\RenderService;
use Astroway\Namespaces\ReportsService;
use Astroway\Namespaces\RetrogradePeriodsService;
use Astroway\Namespaces\RunesService;
use Astroway\Namespaces\SabianSymbolsService;
use Astroway\Namespaces\SolarAcgService;
use Astroway\Namespaces\SolarReturnService;
use Astroway\Namespaces\StreamService;
use Astroway\Namespaces\SunTimesService;
use Astroway\Namespaces\SymbolicDirectionsService;
use Astroway\Namespaces\SynastryService;
use Astroway\Namespaces\TarotService;
use Astroway\Namespaces\TertiaryProgressionsService;
use Astroway\Namespaces\TransitCalendarService;
use Astroway\Namespaces\TransitsService;
use Astroway\Namespaces\TranslateService;
use Astroway\Namespaces\VedicService;
use Astroway\Namespaces\VedicDivisionalService;
use Astroway\Namespaces\WebhooksService;
use Astroway\Namespaces\WellnessService;
use Astroway\Namespaces\WhitelabelService;
use Astroway\Namespaces\ZenithService;
use Astroway\Namespaces\ZiweiService;
use Astroway\Namespaces\ZodiacService;

/**
 * Lazy accessors for typed service namespaces. Each accessor returns a memoized
 * service tied to the Astroway client (constructed once per Astroway instance).
 */
trait HasServices
{
    /** @var array<string, object> */
    private array $services = [];

    public function acg(): AcgService
    {
        return $this->services['acg'] ??= new AcgService($this);
    }

    public function acgZones(): AcgZonesService
    {
        return $this->services['acgZones'] ??= new AcgZonesService($this);
    }

    public function ai(): AiService
    {
        return $this->services['ai'] ??= new AiService($this);
    }

    public function algolMinimum(): AlgolMinimumService
    {
        return $this->services['algolMinimum'] ??= new AlgolMinimumService($this);
    }

    public function almuten(): AlmutenService
    {
        return $this->services['almuten'] ??= new AlmutenService($this);
    }

    public function antiscia(): AntisciaService
    {
        return $this->services['antiscia'] ??= new AntisciaService($this);
    }

    public function arabicParts(): ArabicPartsService
    {
        return $this->services['arabicParts'] ??= new ArabicPartsService($this);
    }

    public function ashtakavarga(): AshtakavargaService
    {
        return $this->services['ashtakavarga'] ??= new AshtakavargaService($this);
    }

    public function aspectBar(): AspectBarService
    {
        return $this->services['aspectBar'] ??= new AspectBarService($this);
    }

    public function aspectTimeline(): AspectTimelineService
    {
        return $this->services['aspectTimeline'] ??= new AspectTimelineService($this);
    }

    public function aspects(): AspectsService
    {
        return $this->services['aspects'] ??= new AspectsService($this);
    }

    public function bazi(): BaziService
    {
        return $this->services['bazi'] ??= new BaziService($this);
    }

    public function business(): BusinessService
    {
        return $this->services['business'] ??= new BusinessService($this);
    }

    public function ccgAnalysis(): CcgAnalysisService
    {
        return $this->services['ccgAnalysis'] ??= new CcgAnalysisService($this);
    }

    public function chart(): ChartService
    {
        return $this->services['chart'] ??= new ChartService($this);
    }

    public function chinese(): ChineseService
    {
        return $this->services['chinese'] ??= new ChineseService($this);
    }

    public function coalescent(): CoalescentService
    {
        return $this->services['coalescent'] ??= new CoalescentService($this);
    }

    public function composite(): CompositeService
    {
        return $this->services['composite'] ??= new CompositeService($this);
    }

    public function cosmobiology(): CosmobiologyService
    {
        return $this->services['cosmobiology'] ??= new CosmobiologyService($this);
    }

    public function cyclicIndex(): CyclicIndexService
    {
        return $this->services['cyclicIndex'] ??= new CyclicIndexService($this);
    }

    public function davison(): DavisonService
    {
        return $this->services['davison'] ??= new DavisonService($this);
    }

    public function destinyMatrix(): DestinyMatrixService
    {
        return $this->services['destinyMatrix'] ??= new DestinyMatrixService($this);
    }

    public function dispositionChains(): DispositionChainsService
    {
        return $this->services['dispositionChains'] ??= new DispositionChainsService($this);
    }

    public function djamaspa(): DjamaspaService
    {
        return $this->services['djamaspa'] ??= new DjamaspaService($this);
    }

    public function draconic(): DraconicService
    {
        return $this->services['draconic'] ??= new DraconicService($this);
    }

    public function eclipseAnalysis(): EclipseAnalysisService
    {
        return $this->services['eclipseAnalysis'] ??= new EclipseAnalysisService($this);
    }

    public function eclipses(): EclipsesService
    {
        return $this->services['eclipses'] ??= new EclipsesService($this);
    }

    public function ephemeris(): EphemerisService
    {
        return $this->services['ephemeris'] ??= new EphemerisService($this);
    }

    public function esoteric(): EsotericService
    {
        return $this->services['esoteric'] ??= new EsotericService($this);
    }

    public function essentialDignities(): EssentialDignitiesService
    {
        return $this->services['essentialDignities'] ??= new EssentialDignitiesService($this);
    }

    public function evolutionary(): EvolutionaryService
    {
        return $this->services['evolutionary'] ??= new EvolutionaryService($this);
    }

    public function family(): FamilyService
    {
        return $this->services['family'] ??= new FamilyService($this);
    }

    public function financial(): FinancialService
    {
        return $this->services['financial'] ??= new FinancialService($this);
    }

    public function firdaria(): FirdariaService
    {
        return $this->services['firdaria'] ??= new FirdariaService($this);
    }

    public function fixedStars(): FixedStarsService
    {
        return $this->services['fixedStars'] ??= new FixedStarsService($this);
    }

    public function forecastCalendar(): ForecastCalendarService
    {
        return $this->services['forecastCalendar'] ??= new ForecastCalendarService($this);
    }

    public function gauquelinSectors(): GauquelinSectorsService
    {
        return $this->services['gauquelinSectors'] ??= new GauquelinSectorsService($this);
    }

    public function geodetic(): GeodeticService
    {
        return $this->services['geodetic'] ??= new GeodeticService($this);
    }

    public function geomancy(): GeomancyService
    {
        return $this->services['geomancy'] ??= new GeomancyService($this);
    }

    public function groupSynastry(): GroupSynastryService
    {
        return $this->services['groupSynastry'] ??= new GroupSynastryService($this);
    }

    public function harmonics(): HarmonicsService
    {
        return $this->services['harmonics'] ??= new HarmonicsService($this);
    }

    public function hd(): HdService
    {
        return $this->services['hd'] ??= new HdService($this);
    }

    public function heliocentric(): HeliocentricService
    {
        return $this->services['heliocentric'] ??= new HeliocentricService($this);
    }

    public function hellenistic(): HellenisticService
    {
        return $this->services['hellenistic'] ??= new HellenisticService($this);
    }

    public function horary(): HoraryService
    {
        return $this->services['horary'] ??= new HoraryService($this);
    }

    public function horizon(): HorizonService
    {
        return $this->services['horizon'] ??= new HorizonService($this);
    }

    public function horoscope(): HoroscopeService
    {
        return $this->services['horoscope'] ??= new HoroscopeService($this);
    }

    public function houses(): HousesService
    {
        return $this->services['houses'] ??= new HousesService($this);
    }

    public function humanDesign(): HumanDesignService
    {
        return $this->services['humanDesign'] ??= new HumanDesignService($this);
    }

    public function hyleg(): HylegService
    {
        return $this->services['hyleg'] ??= new HylegService($this);
    }

    public function iching(): IchingService
    {
        return $this->services['iching'] ??= new IchingService($this);
    }

    public function ingresses(): IngressesService
    {
        return $this->services['ingresses'] ??= new IngressesService($this);
    }

    public function interpret(): InterpretService
    {
        return $this->services['interpret'] ??= new InterpretService($this);
    }

    public function localSpace(): LocalSpaceService
    {
        return $this->services['localSpace'] ??= new LocalSpaceService($this);
    }

    public function lunarCalendar(): LunarCalendarService
    {
        return $this->services['lunarCalendar'] ??= new LunarCalendarService($this);
    }

    public function lunarReturn(): LunarReturnService
    {
        return $this->services['lunarReturn'] ??= new LunarReturnService($this);
    }

    public function match_(): Match_Service
    {
        return $this->services['match_'] ??= new Match_Service($this);
    }

    public function mayan(): MayanService
    {
        return $this->services['mayan'] ??= new MayanService($this);
    }

    public function mcp(): McpService
    {
        return $this->services['mcp'] ??= new McpService($this);
    }

    public function midpointTrees(): MidpointTreesService
    {
        return $this->services['midpointTrees'] ??= new MidpointTreesService($this);
    }

    public function midpoints(): MidpointsService
    {
        return $this->services['midpoints'] ??= new MidpointsService($this);
    }

    public function minorProgressions(): MinorProgressionsService
    {
        return $this->services['minorProgressions'] ??= new MinorProgressionsService($this);
    }

    public function modern(): ModernService
    {
        return $this->services['modern'] ??= new ModernService($this);
    }

    public function moonAspects(): MoonAspectsService
    {
        return $this->services['moonAspects'] ??= new MoonAspectsService($this);
    }

    public function moonPhase(): MoonPhaseService
    {
        return $this->services['moonPhase'] ??= new MoonPhaseService($this);
    }

    public function moonVoc(): MoonVocService
    {
        return $this->services['moonVoc'] ??= new MoonVocService($this);
    }

    public function muhurta(): MuhurtaService
    {
        return $this->services['muhurta'] ??= new MuhurtaService($this);
    }

    public function nakshatras(): NakshatrasService
    {
        return $this->services['nakshatras'] ??= new NakshatrasService($this);
    }

    public function numerology(): NumerologyService
    {
        return $this->services['numerology'] ??= new NumerologyService($this);
    }

    public function palmistry(): PalmistryService
    {
        return $this->services['palmistry'] ??= new PalmistryService($this);
    }

    public function parallelAspects(): ParallelAspectsService
    {
        return $this->services['parallelAspects'] ??= new ParallelAspectsService($this);
    }

    public function parans(): ParansService
    {
        return $this->services['parans'] ??= new ParansService($this);
    }

    public function pet(): PetService
    {
        return $this->services['pet'] ??= new PetService($this);
    }

    public function phaseReturn(): PhaseReturnService
    {
        return $this->services['phaseReturn'] ??= new PhaseReturnService($this);
    }

    public function planetaryCycles(): PlanetaryCyclesService
    {
        return $this->services['planetaryCycles'] ??= new PlanetaryCyclesService($this);
    }

    public function planetaryHours(): PlanetaryHoursService
    {
        return $this->services['planetaryHours'] ??= new PlanetaryHoursService($this);
    }

    public function planetaryPhases(): PlanetaryPhasesService
    {
        return $this->services['planetaryPhases'] ??= new PlanetaryPhasesService($this);
    }

    public function planetaryReturn(): PlanetaryReturnService
    {
        return $this->services['planetaryReturn'] ??= new PlanetaryReturnService($this);
    }

    public function planets(): PlanetsService
    {
        return $this->services['planets'] ??= new PlanetsService($this);
    }

    public function primaryDirections(): PrimaryDirectionsService
    {
        return $this->services['primaryDirections'] ??= new PrimaryDirectionsService($this);
    }

    public function profections(): ProfectionsService
    {
        return $this->services['profections'] ??= new ProfectionsService($this);
    }

    public function progressions(): ProgressionsService
    {
        return $this->services['progressions'] ??= new ProgressionsService($this);
    }

    public function receptions(): ReceptionsService
    {
        return $this->services['receptions'] ??= new ReceptionsService($this);
    }

    public function rectification(): RectificationService
    {
        return $this->services['rectification'] ??= new RectificationService($this);
    }

    public function reference(): ReferenceService
    {
        return $this->services['reference'] ??= new ReferenceService($this);
    }

    public function relocation(): RelocationService
    {
        return $this->services['relocation'] ??= new RelocationService($this);
    }

    public function render(): RenderService
    {
        return $this->services['render'] ??= new RenderService($this);
    }

    public function reports(): ReportsService
    {
        return $this->services['reports'] ??= new ReportsService($this);
    }

    public function retrogradePeriods(): RetrogradePeriodsService
    {
        return $this->services['retrogradePeriods'] ??= new RetrogradePeriodsService($this);
    }

    public function runes(): RunesService
    {
        return $this->services['runes'] ??= new RunesService($this);
    }

    public function sabianSymbols(): SabianSymbolsService
    {
        return $this->services['sabianSymbols'] ??= new SabianSymbolsService($this);
    }

    public function solarAcg(): SolarAcgService
    {
        return $this->services['solarAcg'] ??= new SolarAcgService($this);
    }

    public function solarReturn(): SolarReturnService
    {
        return $this->services['solarReturn'] ??= new SolarReturnService($this);
    }

    public function stream(): StreamService
    {
        return $this->services['stream'] ??= new StreamService($this);
    }

    public function sunTimes(): SunTimesService
    {
        return $this->services['sunTimes'] ??= new SunTimesService($this);
    }

    public function symbolicDirections(): SymbolicDirectionsService
    {
        return $this->services['symbolicDirections'] ??= new SymbolicDirectionsService($this);
    }

    public function synastry(): SynastryService
    {
        return $this->services['synastry'] ??= new SynastryService($this);
    }

    public function tarot(): TarotService
    {
        return $this->services['tarot'] ??= new TarotService($this);
    }

    public function tertiaryProgressions(): TertiaryProgressionsService
    {
        return $this->services['tertiaryProgressions'] ??= new TertiaryProgressionsService($this);
    }

    public function transitCalendar(): TransitCalendarService
    {
        return $this->services['transitCalendar'] ??= new TransitCalendarService($this);
    }

    public function transits(): TransitsService
    {
        return $this->services['transits'] ??= new TransitsService($this);
    }

    public function translate(): TranslateService
    {
        return $this->services['translate'] ??= new TranslateService($this);
    }

    public function vedic(): VedicService
    {
        return $this->services['vedic'] ??= new VedicService($this);
    }

    public function vedicDivisional(): VedicDivisionalService
    {
        return $this->services['vedicDivisional'] ??= new VedicDivisionalService($this);
    }

    public function webhooks(): WebhooksService
    {
        return $this->services['webhooks'] ??= new WebhooksService($this);
    }

    public function wellness(): WellnessService
    {
        return $this->services['wellness'] ??= new WellnessService($this);
    }

    public function whitelabel(): WhitelabelService
    {
        return $this->services['whitelabel'] ??= new WhitelabelService($this);
    }

    public function zenith(): ZenithService
    {
        return $this->services['zenith'] ??= new ZenithService($this);
    }

    public function ziwei(): ZiweiService
    {
        return $this->services['ziwei'] ??= new ZiweiService($this);
    }

    public function zodiac(): ZodiacService
    {
        return $this->services['zodiac'] ??= new ZodiacService($this);
    }

}
